// Auto-generated by RevitGeoSuite.SharedUI.Web.Contracts.Generator
// Do not edit manually.

export interface AvailableCrsRequest {
}

export interface AvailableCrsResponse {
  groups: CrsOptionGroup[]
}

export interface CityGmlExportOptions {
  categoryOverrides: Record<string, string>
  codelistOverrides: Record<string, string>
  schemaVersion: string
}

export interface CityGmlExportPrepareRequest {
  options: CityGmlExportOptions
}

export interface CityGmlExportPrepareResponse {
  crs: string
  featureCount: number
  warnings: string[]
}

export interface CityGmlExportRequest {
  options: CityGmlExportOptions
  outputFolder: string
}

export interface CityGmlExportResponse {
  exportedElements: number
  exportPath: string
  featureCount: number
  files: number
  summary: string
  warnings: string[]
}

export interface CrsOptionEntry {
  areaSummary: string
  epsgCode: number
  name: string
}

export interface CrsOptionGroup {
  entries: CrsOptionEntry[]
  region: string
}

export interface DialogOpenFileRequest {
  initialPath?: string
  title?: string
}

export interface DialogOpenFileResponse {
  error?: string
  path?: string
  paths: string[]
}

export interface DialogOpenFolderRequest {
  initialPath?: string
  title?: string
}

export interface DialogOpenFolderResponse {
  error?: string
  path?: string
}

export interface ExecutionActionResponse {
  error?: string
  success: boolean
}

export interface ExecutionProgressInitialStateRequest {
}

export interface ExecutionProgressInitialStateResponse {
  language: string
  progress: ExecutionProgressPayload
}

export interface ExecutionProgressPayload {
  completedSteps: number
  isCancelling: boolean
  startedAtUtc: string
  statusText: string
  totalSteps: number
}

export interface ExporterCrsPreset {
  displayName: string
  epsg: number
}

export interface ExporterCrsPresetGroup {
  entries: ExporterCrsPreset[]
  region: string
}

export interface ExporterDeleteProfileRequest {
  name: string
  scope: string
}

export interface ExporterEmptyRequest {
}

export interface ExporterInitialStateRequest {
}

export interface ExporterInitialStateResponse {
  coordinateDetail: string
  coordinateStatus: string
  crsPresetGroups: ExporterCrsPresetGroup[]
  documentName: string
  links: ExporterLinkOption[]
  profiles: ExporterProfileOption[]
  schemaProfiles: ExporterNamedOption[]
  settings: ExporterSettingsPayload
  validationPolicies: ExporterNamedOption[]
  version: string
  views: ExporterViewOption[]
}

export interface ExporterLinkOption {
  displayName: string
  id: number
  sourceDocumentName: string
}

export interface ExporterNamedOption {
  name: string
}

export interface ExporterProfileOption {
  displayName: string
  name: string
  scope: string
  settings: ExporterSettingsPayload
}

export interface ExporterRunResponse {
  error?: string
  result?: ExportResultInitialStateResponse
  success: boolean
}

export interface ExporterSaveProfileRequest {
  name: string
  scope: string
  settings: ExporterSettingsPayload
}

export interface ExporterSettingsPayload {
  activeSchemaProfileName: string
  activeValidationPolicyProfileName: string
  coordinateMode: string
  detail: boolean
  fixture: boolean
  generateDiagnosticsReport: boolean
  generatePackageOutput: boolean
  generateQgisArtifacts: boolean
  includeLinkedModels: boolean
  includePackageLegend: boolean
  incrementalExportMode: string
  keep3DTempViewsForDebug: boolean
  launchQgis: boolean
  level: boolean
  opening: boolean
  openOutputFolder: boolean
  outputDirectory: string
  outputFormat: string
  packagingMode: string
  roomCategoryParameterName: string
  sectionBoxAboveFloorMeters: number
  sectionBoxBelowFloorMeters: number
  selectedLinkIds: number[]
  selectedProfileName?: string
  selectedViewIds: number[]
  simplifyEscalatorUnits: boolean
  simplifyStairUnits: boolean
  targetEpsg: number
  unit: boolean
  unitAttributeSource: string
  unitGeometrySource: string
  use3DSectionBoxExport: boolean
  validateAfterWrite: boolean
}

export interface ExporterSubmitResponse {
  accepted: boolean
  error?: string
}

export interface ExporterViewOption {
  displayName: string
  id: number
  levelName: string
  name: string
}

export interface ExportResultFilePayload {
  featureCount: number
  featureType: string
  levelName: string
  outputFilePath: string
  viewName: string
}

export interface ExportResultInitialStateRequest {
}

export interface ExportResultInitialStateResponse {
  canOpenOutputDirectory: boolean
  changes: string[]
  files: ExportResultFilePayload[]
  language: string
  message: string
  outputDirectory: string
  packageLines: string[]
  summary: ExportResultSummaryPayload
  timings: ExportResultTimingPayload[]
  title: string
  warnings: string[]
}

export interface ExportResultSummaryPayload {
  artifactCount: number
  featureCount: number
  packageErrorCount: number
  packageWarningCount: number
  reusedArtifactCount: number
  viewCount: number
  warningCount: number
  writtenArtifactCount: number
}

export interface ExportResultTimingPayload {
  durationMilliseconds: number
  durationText: string
  phaseName: string
}

export interface GeoreferenceApplyRequest {
  confirmExistingSetup: boolean
  crsCode: string
  selectedMeshCodes: string[]
}

export interface GeoreferenceApplyResponse {
  message: string
  success: boolean
}

export interface GeoreferenceBasePointResponse {
  easting: number
  lat: number
  lon: number
  northing: number
  selectedMeshCodes: string[]
}

export interface GeoreferenceBasePointSnapshot {
  estimatedLatitudeDegrees?: number
  estimatedLongitudeDegrees?: number
  name: string
  sharedEastWestFeet?: number
  sharedElevationFeet?: number
  sharedNorthSouthFeet?: number
  xFeet: number
  yFeet: number
  zFeet: number
}

export interface GeoreferenceCrsOriginRequest {
  crsCode: string
}

export interface GeoreferenceCurrentStateRequest {
}

export interface GeoreferenceCurrentStateResponse {
  documentTitle: string
  existingSetupDetected: boolean
  existingSetupMessage: string
  hasDetectedExistingPointSetup: boolean
  hasStoredGeoInfo: boolean
  isReadOnly: boolean
  isSupportedDocument: boolean
  projectBasePoint: GeoreferenceBasePointSnapshot
  projectPosition: GeoreferenceProjectPositionSnapshot
  siteLatitudeDegrees?: number
  siteLongitudeDegrees?: number
  statusMessage: string
  storedCrsEpsgCode?: number
  storedOriginLatitude?: number
  storedOriginLongitude?: number
  storedTrueNorthAngleDegrees?: number
  surveyPoint: GeoreferenceBasePointSnapshot
}

export interface GeoreferenceGridCandidate {
  isPrimary: boolean
  isSeedCandidate: boolean
  tileId: string
}

export interface GeoreferenceGridCandidatesRequest {
  crsCode: string
  lat: number
  lon: number
}

export interface GeoreferenceGridCandidatesResponse {
  candidates: GeoreferenceGridCandidate[]
  centerLat: number
  centerLon: number
  overlayGeoJson: string
}

export interface GeoreferenceHasUndoResponse {
  hasSnapshot: boolean
  summary: string
}

export interface GeoreferencePoint {
  lat: number
  lon: number
}

export interface GeoreferenceProjectPositionSnapshot {
  angleDegrees: number
  eastWestFeet: number
  elevationFeet: number
  northSouthFeet: number
}

export interface GeoreferenceResolveBasePointRequest {
  crsCode: string
  selectedMeshCodes: string[]
}

export interface GeoreferenceRevertRequest {
}

export interface GeoreferenceRevertResponse {
  success: boolean
  summary: string
}

export interface GisExportCategoryColor {
  category: string
  color: string
}

export interface GisExportFileAssignment {
  category: string
  levelId?: number
  path: string
}

export interface GisExportOptionsRequest {
}

export interface GisExportOptionsResponse {
  defaultLevelId?: number
  levels: GisLevelOption[]
}

export interface GisExportRequest {
  basemapName: string
  categoryColors: GisExportCategoryColor[]
  fileAssignments: GisExportFileAssignment[]
  outputFolder: string
  path: string
  paths: string[]
}

export interface GisLevelOption {
  elevationFeet: number
  id: number
  name: string
}

export interface HelpDocumentPayload {
  html: string
  isFallback: boolean
  language: string
  title: string
  topic: string
}

export interface HelpInitialStateRequest {
}

export interface HelpInitialStateResponse {
  contextLabel: string
  currentTopic: string
  document: HelpDocumentPayload
  language: string
  productName: string
  topics: HelpTopicOption[]
  version: string
}

export interface HelpOpenTopicRequest {
  language: string
  topic: string
}

export interface HelpTopicOption {
  label: string
  topic: string
}

export interface JobCancelRequest {
  jobId: string
}

export interface JobCancelResponse {
  cancelled: boolean
}

export interface JobCompleted {
  jobId: string
  result?: unknown
}

export interface JobFailed {
  cancelled: boolean
  error: string
  jobId: string
}

export interface JobProgress {
  current: number
  jobId: string
  message?: string
  percent: number
  phase?: string
  total: number
}

export interface JobStarted {
  jobId: string
}

export interface LocalizationGetAllRequest {
}

export interface LocalizationSetLanguageRequest {
  language: string
}

export interface LocalizationSetLanguageResponse {
  error?: string
  language: string
  strings: Record<string, string>
  success: boolean
}

export interface LocalizationStrings {
  language: string
  strings: Record<string, string>
}

export interface MeshOverlayRequest {
}

export interface MeshOverlayResponse {
  centerLatitude?: number
  centerLongitude?: number
  error?: string
  neighborMeshCodes: string[]
  overlayGeoJson?: string
  primaryMeshCode?: string
  statusMessage: string
}

export interface NavigateEvent {
  route: string
}

export interface NavigateRequest {
  route: string
}

export interface OsmBuildingsImportRequest {
  ionToken: string
  mode: string
  radiusMeters: number
}

export interface OsmBuildingsImportResponse {
  groups: number
  importedElements: number
  summary: string
  warnings: string[]
}

export interface PlateauAreaLocationRequest {
  areaCode: string
}

export interface PlateauAreaLocationResponse {
  areaCode: string
  latitude: number
  longitude: number
  zoom: number
}

export interface PlateauCkanArea {
  code: string
  codeLabel: string
  displayLabel: string
  englishName: string
  latestYear: string
  latitude?: number
  longitude?: number
  searchTokens: string
  slugByYear: Record<string, string>
  years: string[]
}

export interface PlateauCkanCatalogResponse {
  areaCount: number
  areas: PlateauCkanArea[]
}

export interface PlateauCkanDownloadCheckResponse {
  existingUrls: string[]
}

export interface PlateauCkanDownloadRequest {
  areaName: string
  code: string
  destinationFolder: string
  force: boolean
  resourceUrls: string[]
  year: string
}

export interface PlateauCkanDownloadResponse {
  filesExtracted: number
  folderPath: string
  warnings: string[]
}

export interface PlateauCkanResource {
  defaultSelected: boolean
  featureKey: string
  featureLabel: string
  fileName: string
  id: string
  lod: string
  sizeBytes: number
  url: string
}

export interface PlateauCkanResourcesRequest {
  slug: string
}

export interface PlateauCkanResourcesResponse {
  resources: PlateauCkanResource[]
  slug: string
}

export interface PlateauContextExportFormats {
  dxf: boolean
  shapefile: boolean
}

export interface PlateauContextExportOptions {
  dxf?: boolean
  formats: PlateauContextExportFormats
  includeContext: boolean
  includeKiban: boolean
  includeRevitModel: boolean
  shapefile?: boolean
}

export interface PlateauContextExportPreviewResponse {
  crs: string
  featureCount: number
  perLayerCounts: Record<string, number>
  warnings: string[]
}

export interface PlateauContextExportRequest {
  additionalGreenLandUseTokens?: string[]
  featureTypes?: string[]
  folderPath: string
  greenLandUseTokens?: string[]
  kibanFolderPath: string
  kibanLayers?: string[]
  options: PlateauContextExportOptions
  outputFolder: string
  path?: string
  selectedFeatureTypes?: string[]
  selectedKibanLayers: string[]
  selectedTileIds: string[]
  tileIds?: string[]
}

export interface PlateauContextExportResponse {
  exportedElements: number
  exportedFeatures: number
  filePaths: string[]
  files: number
  summary: string
  warnings: string[]
}

export interface PlateauImportRequest {
  mode: string
  path: string
  tileIds: string[]
}

export interface PlateauOnlineArea {
  aliases: string[]
  city: string
  code: string
  codeLabel: string
  displayLabel: string
  hasBuildings: boolean
  label: string
  latitude?: number
  longitude?: number
  prefecture: string
  searchTokens: string
  ward: string
}

export interface PlateauOnlineAreaGridSelection {
  areaCode: string
  gridIds: string[]
}

export interface PlateauOnlineCatalogRequest {
}

export interface PlateauOnlineCatalogResponse {
  areaCount: number
  areas: PlateauOnlineArea[]
  datasetCount: number
  dracoAvailable: boolean
  dracoMessage: string
  suggestion?: PlateauOnlineSuggestion
}

export interface PlateauOnlineGrid {
  areaCodes: string[]
  areaLabels: string[]
  geometry?: unknown
  id: string
  label: string
  lod: string
  texture?: boolean
}

export interface PlateauOnlineGridsRequest {
  areaCode: string
  areaCodes: string[]
}

export interface PlateauOnlineGridsResponse {
  areaCode: string
  areaCodes: string[]
  areaLabel: string
  areaLabels: string[]
  datasetLod: string
  datasetTexture?: boolean
  gridCount: number
  grids: PlateauOnlineGrid[]
}

export interface PlateauOnlineImportAreaResult {
  areaCode: string
  areaLabel: string
  groups: number
  importedElements: number
  warnings: string[]
}

export interface PlateauOnlineImportRequest {
  areaCode: string
  areaCodes: string[]
  areaSelections: PlateauOnlineAreaGridSelection[]
  categories: string[]
  gridIds: string[]
  mode: string
}

export interface PlateauOnlineImportResponse {
  areaCode: string
  areaLabel: string
  areaResults: PlateauOnlineImportAreaResult[]
  groups: number
  importedElements: number
  mode: string
  summary: string
  warnings: string[]
}

export interface PlateauOnlineSuggestion {
  areaCode: string
  areaLabel: string
  areas: PlateauOnlineSuggestionArea[]
  codeLabel: string
  displayLabel: string
  latitude: number
  longitude: number
  message: string
  source: string
}

export interface PlateauOnlineSuggestionArea {
  areaCode: string
  codeLabel: string
  displayLabel: string
  nearestDistanceMeters: number
}

export interface PlateauScanRequest {
  path: string
}

export interface PreviewAssignmentRequest {
  category: string
  floorTypeNames: string[]
}

export interface PreviewAssignmentSummaryPayload {
  assignedFloorTypeCount: number
  floorTypeCount: number
  hasPendingAssignments: boolean
  pendingMessage: string
  rows: PreviewCategoryAssignmentRowPayload[]
  sourceLabel: string
  unassignedFloorTypeCount: number
}

export interface PreviewBoundsPayload {
  isEmpty: boolean
  maxX: number
  maxY: number
  minX: number
  minY: number
}

export interface PreviewCategoryAssignmentRowPayload {
  category: string
  floorTypeName: string
  isUnassigned: boolean
  parsedCandidate: string
  sampleUnits: string[]
  status: string
  unitCount: number
  usesOverride: boolean
  viewCount: number
  viewNames: string[]
}

export interface PreviewClearAssignmentRequest {
  floorTypeNames: string[]
}

export interface PreviewFeaturePayload {
  category: string
  exportId: string
  featureType: string
  fillColor: string
  floorTypeName: string
  geometryType: string
  hasWarning: boolean
  index: number
  isUnassignedFloor: boolean
  name: string
  parsedZoneCandidate: string
  points: PreviewPointPayload[]
  restriction: string
  rings: PreviewPointPayload[][]
  searchText: string
  sourceLabel: string
  strokeColor: string
  supportsFloorCategoryAssignment: boolean
  usesFloorCategoryOverride: boolean
}

export interface PreviewInitialStateRequest {
}

export interface PreviewInitialStateResponse {
  assignmentSummary: PreviewAssignmentSummaryPayload
  coordinateSummary: string
  currentView?: PreviewViewPayload
  language: string
  readinessIssueCount: number
  readinessUnassignedFloorTypeCount: number
  readinessWarningCount: number
  supportedCategories: string[]
  views: PreviewViewOption[]
}

export interface PreviewLegendPayload {
  count: number
  fillColor: string
  label: string
}

export interface PreviewLoadViewRequest {
  viewId: number
}

export interface PreviewPointPayload {
  x: number
  y: number
}

export interface PreviewUnassignedFloorPayload {
  floorTypeName: string
  parsedCandidate: string
  unitCount: number
}

export interface PreviewViewOption {
  displayName: string
  id: number
  name: string
}

export interface PreviewViewPayload {
  assignmentPendingMessage: string
  assignmentSourceLabel: string
  bounds: PreviewBoundsPayload
  features: PreviewFeaturePayload[]
  hasPendingAssignments: boolean
  instruction: string
  legend: PreviewLegendPayload[]
  levelName: string
  quickSummary: string
  unassignedFloors: PreviewUnassignedFloorPayload[]
  viewId: number
  viewName: string
  warnings: string[]
}

export interface ReadinessExportItem {
  detail: string
  isSatisfied: boolean
  statusText: string
  title: string
}

export interface ReadinessExportSummary {
  items: ReadinessExportItem[]
  status: string
  statusMessage: string
  statusTitle: string
}

export interface ReadinessFinding {
  code: string
  message: string
  severity: string
}

export interface ReadinessStatusRequest {
}

export interface ReadinessStatusResponse {
  error?: string
  exportReadiness: ReadinessExportSummary
  findings: ReadinessFinding[]
  status: string
  statusMessage: string
}

export interface Tiles3DExportOptions {
  geoidOffset: number
  geometryMode: string
  lod: string
  preciseCrs: boolean
  selectedLinkUniqueIds: string[]
  splitByLevel: boolean
}

export interface Tiles3DExportOptionsRequest {}

export interface Tiles3DExportOptionsResponse {
  links: Tiles3DLinkOption[]
}

export interface Tiles3DLinkOption {
  description: string
  title: string
  uniqueId: string
}

export interface Tiles3DExportPrepareRequest {
  options: Tiles3DExportOptions
  scope: string
}

export interface Tiles3DExportPrepareResponse {
  crs: string
  elementCount: number
  triangleCount: number
  warnings: string[]
}

export interface Tiles3DExportRequest {
  options: Tiles3DExportOptions
  outputFolder: string
  scope: string
}

export interface Tiles3DExportResponse {
  exportedElements: number
  files: number
  summary: string
  tilesetPath: string
  triangleCount: number
  warnings: string[]
}

export interface RpcMethods {
  'citygml.export': { request: CityGmlExportRequest; response: JobStarted }
  'citygml.export.prepare': { request: CityGmlExportPrepareRequest; response: CityGmlExportPrepareResponse }
  'dialog.openFile': { request: DialogOpenFileRequest; response: DialogOpenFileResponse }
  'dialog.openFolder': { request: DialogOpenFolderRequest; response: DialogOpenFolderResponse }
  'floorplan.cancel': { request: ExporterEmptyRequest; response: void }
  'floorplan.deleteProfile': { request: ExporterDeleteProfileRequest; response: ExporterInitialStateResponse }
  'floorplan.execution.progress.getInitialState': { request: ExecutionProgressInitialStateRequest; response: ExecutionProgressInitialStateResponse }
  'floorplan.execution.result.getInitialState': { request: ExportResultInitialStateRequest; response: ExportResultInitialStateResponse }
  'floorplan.execution.result.openOutputFolder': { request: ExporterEmptyRequest; response: ExecutionActionResponse }
  'floorplan.getInitialState': { request: ExporterInitialStateRequest; response: ExporterInitialStateResponse }
  'floorplan.preparePreview': { request: ExporterSettingsPayload; response: PreviewInitialStateResponse }
  'floorplan.preview.assignCategory': { request: PreviewAssignmentRequest; response: PreviewViewPayload }
  'floorplan.preview.clearAssignment': { request: PreviewClearAssignmentRequest; response: PreviewViewPayload }
  'floorplan.preview.discardAssignments': { request: ExporterEmptyRequest; response: PreviewViewPayload }
  'floorplan.preview.getInitialState': { request: PreviewInitialStateRequest; response: PreviewInitialStateResponse }
  'floorplan.preview.loadView': { request: PreviewLoadViewRequest; response: PreviewViewPayload }
  'floorplan.preview.saveAssignments': { request: ExporterEmptyRequest; response: PreviewViewPayload }
  'floorplan.run': { request: ExporterSettingsPayload; response: ExporterRunResponse }
  'floorplan.saveProfile': { request: ExporterSaveProfileRequest; response: ExporterInitialStateResponse }
  'georeference.apply': { request: GeoreferenceApplyRequest; response: GeoreferenceApplyResponse }
  'georeference.getAvailableCrs': { request: AvailableCrsRequest; response: AvailableCrsResponse }
  'georeference.getCrsOrigin': { request: GeoreferenceCrsOriginRequest; response: GeoreferencePoint }
  'georeference.getCurrentState': { request: GeoreferenceCurrentStateRequest; response: GeoreferenceCurrentStateResponse }
  'georeference.getGridCandidates': { request: GeoreferenceGridCandidatesRequest; response: GeoreferenceGridCandidatesResponse }
  'georeference.hasUndoSnapshot': { request: GeoreferenceRevertRequest; response: GeoreferenceHasUndoResponse }
  'georeference.resolveGridBasePoint': { request: GeoreferenceResolveBasePointRequest; response: GeoreferenceBasePointResponse }
  'georeference.revert': { request: GeoreferenceRevertRequest; response: GeoreferenceRevertResponse }
  'gis.export': { request: GisExportRequest; response: JobStarted }
  'gis.exportOptions': { request: GisExportOptionsRequest; response: GisExportOptionsResponse }
  'job.cancel': { request: JobCancelRequest; response: JobCancelResponse }
  'localization.getAll': { request: LocalizationGetAllRequest; response: LocalizationStrings }
  'localization.setLanguage': { request: LocalizationSetLanguageRequest; response: LocalizationSetLanguageResponse }
  'mesh.getOverlay': { request: MeshOverlayRequest; response: MeshOverlayResponse }
  'osm.importBuildings': { request: OsmBuildingsImportRequest; response: JobStarted }
  'plateau.areaLocation': { request: PlateauAreaLocationRequest; response: PlateauAreaLocationResponse }
  'plateau.exportContext': { request: PlateauContextExportRequest; response: JobStarted }
  'plateau.exportContext.prepare': { request: PlateauContextExportRequest; response: JobStarted }
  'plateau.importTiles': { request: PlateauImportRequest; response: JobStarted }
  'plateau.onlineCatalog': { request: PlateauOnlineCatalogRequest; response: JobStarted }
  'plateau.onlineGrids': { request: PlateauOnlineGridsRequest; response: JobStarted }
  'plateau.onlineImport': { request: PlateauOnlineImportRequest; response: JobStarted }
  'plateau.scanFolder': { request: PlateauScanRequest; response: JobStarted }
  'readiness.getStatus': { request: ReadinessStatusRequest; response: ReadinessStatusResponse }
  'tiles3d.export': { request: Tiles3DExportRequest; response: JobStarted }
  'tiles3d.export.prepare': { request: Tiles3DExportPrepareRequest; response: Tiles3DExportPrepareResponse }
  'tiles3d.exportOptions': { request: Tiles3DExportOptionsRequest; response: Tiles3DExportOptionsResponse }
  'window.navigate': { request: NavigateRequest; response: void }
}

export interface RpcEvents {
  'floorplan.execution.progress.updated': ExecutionProgressPayload
  'job.completed': JobCompleted
  'job.failed': JobFailed
  'job.progress': JobProgress
  'navigate': NavigateEvent
}

