// Auto-generated by RevitGeoSuite.SharedUI.Web.Contracts.Generator
// Do not edit manually.

export interface CityGmlExportOptions {
  categoryOverrides: Record<string, string>
  codelistOverrides: Record<string, string>
  schemaVersion: string
}

export interface CityGmlExportPrepareRequest {
  options: CityGmlExportOptions
}

export interface CityGmlExportPrepareResponse {
  crs: string
  featureCount: number
  warnings: string[]
}

export interface CityGmlExportRequest {
  options: CityGmlExportOptions
  outputFolder: string
}

export interface CityGmlExportResponse {
  exportedElements: number
  exportPath: string
  featureCount: number
  files: number
  summary: string
  warnings: string[]
}

export interface DialogOpenFolderRequest {
  initialPath?: string
  title?: string
}

export interface DialogOpenFolderResponse {
  error?: string
  path?: string
}

export interface GeoreferenceApplyRequest {
  confirmExistingSetup: boolean
  crsCode: string
  selectedMeshCodes: string[]
}

export interface GeoreferenceApplyResponse {
  message: string
  success: boolean
}

export interface GeoreferenceBasePointResponse {
  easting: number
  lat: number
  lon: number
  northing: number
  selectedMeshCodes: string[]
}

export interface GeoreferenceBasePointSnapshot {
  estimatedLatitudeDegrees?: number
  estimatedLongitudeDegrees?: number
  name: string
  sharedEastWestFeet?: number
  sharedElevationFeet?: number
  sharedNorthSouthFeet?: number
  xFeet: number
  yFeet: number
  zFeet: number
}

export interface GeoreferenceCrsOriginRequest {
  crsCode: string
}

export interface GeoreferenceCurrentStateRequest {
}

export interface GeoreferenceCurrentStateResponse {
  documentTitle: string
  existingSetupDetected: boolean
  existingSetupMessage: string
  hasDetectedExistingPointSetup: boolean
  hasStoredGeoInfo: boolean
  isReadOnly: boolean
  isSupportedDocument: boolean
  projectBasePoint: GeoreferenceBasePointSnapshot
  projectPosition: GeoreferenceProjectPositionSnapshot
  siteLatitudeDegrees?: number
  siteLongitudeDegrees?: number
  statusMessage: string
  storedCrsEpsgCode?: number
  storedOriginLatitude?: number
  storedOriginLongitude?: number
  storedTrueNorthAngleDegrees?: number
  surveyPoint: GeoreferenceBasePointSnapshot
}

export interface GeoreferenceGridCandidate {
  isPrimary: boolean
  isSeedCandidate: boolean
  tileId: string
}

export interface GeoreferenceGridCandidatesRequest {
  crsCode: string
  lat: number
  lon: number
}

export interface GeoreferenceGridCandidatesResponse {
  candidates: GeoreferenceGridCandidate[]
  centerLat: number
  centerLon: number
  overlayGeoJson: string
}

export interface GeoreferencePoint {
  lat: number
  lon: number
}

export interface GeoreferenceProjectPositionSnapshot {
  angleDegrees: number
  eastWestFeet: number
  elevationFeet: number
  northSouthFeet: number
}

export interface GeoreferenceResolveBasePointRequest {
  crsCode: string
  selectedMeshCodes: string[]
}

export interface JobCancelRequest {
  jobId: string
}

export interface JobCancelResponse {
  cancelled: boolean
}

export interface JobCompleted {
  jobId: string
  result?: unknown
}

export interface JobFailed {
  cancelled: boolean
  error: string
  jobId: string
}

export interface JobProgress {
  current: number
  jobId: string
  message?: string
  percent: number
  phase?: string
  total: number
}

export interface JobStarted {
  jobId: string
}

export interface LocalizationGetAllRequest {
}

export interface LocalizationSetLanguageRequest {
  language: string
}

export interface LocalizationSetLanguageResponse {
  error?: string
  language: string
  strings: Record<string, string>
  success: boolean
}

export interface LocalizationStrings {
  language: string
  strings: Record<string, string>
}

export interface MeshOverlayRequest {
}

export interface MeshOverlayResponse {
  centerLatitude?: number
  centerLongitude?: number
  error?: string
  neighborMeshCodes: string[]
  overlayGeoJson?: string
  primaryMeshCode?: string
  statusMessage: string
}

export interface NavigateEvent {
  route: string
}

export interface NavigateRequest {
  route: string
}

export interface PlateauCkanArea {
  code: string
  codeLabel: string
  displayLabel: string
  englishName: string
  latestYear: string
  latitude?: number
  longitude?: number
  searchTokens: string
  slugByYear: Record<string, string>
  years: string[]
}

export interface PlateauCkanCatalogResponse {
  areaCount: number
  areas: PlateauCkanArea[]
}

export interface PlateauCkanDownloadCheckResponse {
  existingUrls: string[]
}

export interface PlateauCkanDownloadRequest {
  areaName: string
  code: string
  destinationFolder: string
  force: boolean
  resourceUrls: string[]
  year: string
}

export interface PlateauCkanDownloadResponse {
  filesExtracted: number
  folderPath: string
  warnings: string[]
}

export interface PlateauCkanResource {
  defaultSelected: boolean
  featureKey: string
  featureLabel: string
  fileName: string
  id: string
  lod: string
  sizeBytes: number
  url: string
}

export interface PlateauCkanResourcesRequest {
  slug: string
}

export interface PlateauCkanResourcesResponse {
  resources: PlateauCkanResource[]
  slug: string
}

export interface PlateauContextExportFormats {
  dxf: boolean
  shapefile: boolean
}

export interface PlateauContextExportOptions {
  dxf?: boolean
  formats: PlateauContextExportFormats
  includeContext: boolean
  includeKiban: boolean
  includeRevitModel: boolean
  shapefile?: boolean
}

export interface PlateauContextExportPreviewResponse {
  crs: string
  featureCount: number
  perLayerCounts: Record<string, number>
  warnings: string[]
}

export interface PlateauContextExportRequest {
  additionalGreenLandUseTokens?: string[]
  featureTypes?: string[]
  folderPath: string
  greenLandUseTokens?: string[]
  kibanFolderPath: string
  kibanLayers?: string[]
  options: PlateauContextExportOptions
  outputFolder: string
  path?: string
  selectedFeatureTypes?: string[]
  selectedKibanLayers: string[]
  selectedTileIds: string[]
  tileIds?: string[]
}

export interface PlateauContextExportResponse {
  exportedElements: number
  exportedFeatures: number
  filePaths: string[]
  files: number
  summary: string
  warnings: string[]
}

export interface PlateauImportRequest {
  mode: string
  path: string
  tileIds: string[]
}

export interface PlateauOnlineArea {
  aliases: string[]
  city: string
  code: string
  codeLabel: string
  displayLabel: string
  hasBuildings: boolean
  label: string
  latitude?: number
  longitude?: number
  prefecture: string
  searchTokens: string
  ward: string
}

export interface PlateauOnlineAreaGridSelection {
  areaCode: string
  gridIds: string[]
}

export interface PlateauOnlineCatalogRequest {
}

export interface PlateauOnlineCatalogResponse {
  areaCount: number
  areas: PlateauOnlineArea[]
  datasetCount: number
  dracoAvailable: boolean
  dracoMessage: string
  suggestion?: PlateauOnlineSuggestion
}

export interface PlateauOnlineGrid {
  areaCodes: string[]
  areaLabels: string[]
  geometry?: unknown
  id: string
  label: string
  lod: string
  texture?: boolean
}

export interface PlateauOnlineGridsRequest {
  areaCode: string
  areaCodes: string[]
}

export interface PlateauOnlineGridsResponse {
  areaCode: string
  areaCodes: string[]
  areaLabel: string
  areaLabels: string[]
  datasetLod: string
  datasetTexture?: boolean
  gridCount: number
  grids: PlateauOnlineGrid[]
}

export interface PlateauOnlineImportAreaResult {
  areaCode: string
  areaLabel: string
  groups: number
  importedElements: number
  warnings: string[]
}

export interface PlateauOnlineImportRequest {
  areaCode: string
  areaCodes: string[]
  areaSelections: PlateauOnlineAreaGridSelection[]
  categories: string[]
  gridIds: string[]
  mode: string
}

export interface PlateauOnlineImportResponse {
  areaCode: string
  areaLabel: string
  areaResults: PlateauOnlineImportAreaResult[]
  groups: number
  importedElements: number
  mode: string
  summary: string
  warnings: string[]
}

export interface PlateauOnlineSuggestion {
  areaCode: string
  areaLabel: string
  areas: PlateauOnlineSuggestionArea[]
  codeLabel: string
  displayLabel: string
  latitude: number
  longitude: number
  message: string
  source: string
}

export interface PlateauOnlineSuggestionArea {
  areaCode: string
  codeLabel: string
  displayLabel: string
  nearestDistanceMeters: number
}

export interface PlateauScanRequest {
  path: string
}

export interface ReadinessExportItem {
  detail: string
  isSatisfied: boolean
  statusText: string
  title: string
}

export interface ReadinessExportSummary {
  items: ReadinessExportItem[]
  status: string
  statusMessage: string
  statusTitle: string
}

export interface ReadinessFinding {
  code: string
  message: string
  severity: string
}

export interface ReadinessStatusRequest {
}

export interface ReadinessStatusResponse {
  error?: string
  exportReadiness: ReadinessExportSummary
  findings: ReadinessFinding[]
  status: string
  statusMessage: string
}

export interface Tiles3DExportOptions {
  geoidOffset: number
  geometryMode: string
  lod: string
  preciseCrs: boolean
  splitByLevel: boolean
}

export interface Tiles3DExportPrepareRequest {
  options: Tiles3DExportOptions
  scope: string
}

export interface Tiles3DExportPrepareResponse {
  crs: string
  elementCount: number
  triangleCount: number
  warnings: string[]
}

export interface Tiles3DExportRequest {
  options: Tiles3DExportOptions
  outputFolder: string
  scope: string
}

export interface Tiles3DExportResponse {
  exportedElements: number
  files: number
  summary: string
  tilesetPath: string
  triangleCount: number
  warnings: string[]
}

export interface RpcMethods {
  'citygml.export': { request: CityGmlExportRequest; response: JobStarted }
  'citygml.export.prepare': { request: CityGmlExportPrepareRequest; response: CityGmlExportPrepareResponse }
  'dialog.openFolder': { request: DialogOpenFolderRequest; response: DialogOpenFolderResponse }
  'georeference.apply': { request: GeoreferenceApplyRequest; response: GeoreferenceApplyResponse }
  'georeference.getCrsOrigin': { request: GeoreferenceCrsOriginRequest; response: GeoreferencePoint }
  'georeference.getCurrentState': { request: GeoreferenceCurrentStateRequest; response: GeoreferenceCurrentStateResponse }
  'georeference.getGridCandidates': { request: GeoreferenceGridCandidatesRequest; response: GeoreferenceGridCandidatesResponse }
  'georeference.resolveGridBasePoint': { request: GeoreferenceResolveBasePointRequest; response: GeoreferenceBasePointResponse }
  'job.cancel': { request: JobCancelRequest; response: JobCancelResponse }
  'localization.getAll': { request: LocalizationGetAllRequest; response: LocalizationStrings }
  'localization.setLanguage': { request: LocalizationSetLanguageRequest; response: LocalizationSetLanguageResponse }
  'mesh.getOverlay': { request: MeshOverlayRequest; response: MeshOverlayResponse }
  'plateau.exportContext': { request: PlateauContextExportRequest; response: JobStarted }
  'plateau.exportContext.prepare': { request: PlateauContextExportRequest; response: JobStarted }
  'plateau.importTiles': { request: PlateauImportRequest; response: JobStarted }
  'plateau.onlineCatalog': { request: PlateauOnlineCatalogRequest; response: JobStarted }
  'plateau.onlineGrids': { request: PlateauOnlineGridsRequest; response: JobStarted }
  'plateau.onlineImport': { request: PlateauOnlineImportRequest; response: JobStarted }
  'plateau.scanFolder': { request: PlateauScanRequest; response: JobStarted }
  'readiness.getStatus': { request: ReadinessStatusRequest; response: ReadinessStatusResponse }
  'tiles3d.export': { request: Tiles3DExportRequest; response: JobStarted }
  'tiles3d.export.prepare': { request: Tiles3DExportPrepareRequest; response: Tiles3DExportPrepareResponse }
  'window.navigate': { request: NavigateRequest; response: void }
}

export interface RpcEvents {
  'job.completed': JobCompleted
  'job.failed': JobFailed
  'job.progress': JobProgress
  'navigate': NavigateEvent
}

