using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace RevitGeoSuite.SharedUI.Localization;

public sealed class UiLocalizer : INotifyPropertyChanged
{
    private readonly UiSettingsStore settingsStore = new UiSettingsStore();
    private readonly IReadOnlyDictionary<UiLanguage, IReadOnlyDictionary<string, string>> dictionaries;
    private UiLanguage currentLanguage;

    private UiLocalizer()
    {
        dictionaries = CreateDictionaries();
        currentLanguage = settingsStore.Load();
    }

    public static UiLocalizer Instance { get; } = new UiLocalizer();

    public event PropertyChangedEventHandler? PropertyChanged;

    public UiLanguage CurrentLanguage => currentLanguage;

    public bool IsEnglish => currentLanguage == UiLanguage.English;

    public bool IsJapanese => currentLanguage == UiLanguage.Japanese;

    public bool CanSwitchToEnglish => !IsEnglish;

    public bool CanSwitchToJapanese => !IsJapanese;

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        if (dictionaries.TryGetValue(currentLanguage, out IReadOnlyDictionary<string, string>? currentDictionary) &&
            currentDictionary.TryGetValue(key, out string? localizedValue))
        {
            return localizedValue;
        }

        if (dictionaries.TryGetValue(UiLanguage.English, out IReadOnlyDictionary<string, string>? englishDictionary) &&
            englishDictionary.TryGetValue(key, out string? englishValue))
        {
            return englishValue;
        }

        return key;
    }

    public void SetLanguage(UiLanguage language)
    {
        if (currentLanguage == language)
        {
            return;
        }

        currentLanguage = language;
        settingsStore.Save(language);
        RaiseChanged(nameof(CurrentLanguage));
        RaiseChanged(nameof(IsEnglish));
        RaiseChanged(nameof(IsJapanese));
        RaiseChanged(nameof(CanSwitchToEnglish));
        RaiseChanged(nameof(CanSwitchToJapanese));
        RaiseChanged("Item[]");
    }

    private void RaiseChanged(string propertyName)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    private static IReadOnlyDictionary<UiLanguage, IReadOnlyDictionary<string, string>> CreateDictionaries()
    {
        return new Dictionary<UiLanguage, IReadOnlyDictionary<string, string>>
        {
            [UiLanguage.English] = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["App.ProductTitle"] = "Revit Geo Suite",
                ["App.ShortTitle"] = "Geo Suite",
                ["Common.Back"] = "Back",
                ["Common.Next"] = "Next",
                ["Common.Close"] = "Close",
                ["Common.Apply"] = "Apply",
                ["Common.Browse"] = "Browse...",
                ["Common.Search"] = "Search",
                ["Common.Clear"] = "Clear",
                ["Common.LoadPreview"] = "Load Preview",
                ["Common.ImportContext"] = "Import Context",
                ["Common.PrepareExport"] = "Prepare Export",
                ["Common.Export3DTiles"] = "Export 3D Tiles",
                ["Common.ExportCityGml"] = "Export CityGML",
                ["Common.CopyMesh"] = "Copy Mesh",
                ["Common.SaveCanonicalMesh"] = "Save Canonical Mesh",
                ["Common.ScanFolder"] = "Scan Folder",
                ["Common.Preview"] = "Preview",
                ["Common.Yes"] = "Yes",
                ["Common.No"] = "No",
                ["Language.English"] = "EN",
                ["Language.Japanese"] = "日本語",
                ["Language.Label"] = "Language",
                ["Nav.Georeference"] = "GEO",
                ["Nav.PlateauImport"] = "PLT",
                ["Nav.MeshInspector"] = "MSH",
                ["Nav.Validation"] = "CHK",
                ["Nav.Tiles3DExport"] = "3DT",
                ["Nav.CityGmlExport"] = "GML",
                ["Module.Georeference"] = "Georeference",
                ["Module.PlateauImport"] = "PLATEAU Import",
                ["Module.MeshInspector"] = "Mesh",
                ["Module.Validation"] = "Validation",
                ["Module.Tiles3DExport"] = "3D Tiles",
                ["Module.CityGmlExport"] = "CityGML",
                ["Georef.Step.CurrentState"] = "Current State",
                ["Georef.Step.Crs"] = "CRS",
                ["Georef.Step.SiteReference"] = "Site Reference",
                ["Georef.Step.Review"] = "Review",
                ["Georef.Step.Intent"] = "Intent",
                ["Georef.Step.Preview"] = "Preview",
                ["Georef.Sidebar.ProjectContext"] = "Project Context",
                ["Georef.Sidebar.PrimaryAnchor"] = "Primary Apply Anchor",
                ["Georef.Sidebar.WorkingPoint"] = "Working Project Base Point",
                ["Georef.Sidebar.Alerts"] = "Alerts",
                ["Georef.Section.StepperHint"] = "Follow the guided setup. Only the active step stays in focus; supporting detail moves into the right panel.",
                ["Georef.Section.MapContext"] = "Map search, zoom, and markers stay available for context while you define the main anchor and any optional working point.",
                ["Georef.Section.TechnicalDetails"] = "Technical Details",
                ["Georef.Action.ZoomSite"] = "Zoom To Site",
                ["Georef.Action.ZoomProjectPoint"] = "Zoom To Project Base Point",
                ["Georef.Action.UseCoordinates"] = "Use Coordinates",
                ["Georef.Action.RefreshCurrent"] = "Refresh Current Survey Point",
                ["Georef.Action.ApplyManual"] = "Apply is always manual. Review the preview carefully before committing changes.",
                ["Georef.Simple.Step.Setup"] = "CRS + Setup",
                ["Georef.Simple.StepDescription.NewProject"] = "Pick the project CRS, then either enter the Project Base Point offset or choose nearby PLATEAU grids. Survey Point represents the CRS origin.",
                ["Georef.Simple.StepDescription.Existing"] = "Confirm the current Survey Point and Project Base Point setup, then save canonical metadata from those existing positions.",
                ["Georef.Simple.Mode.NewProject.Title"] = "New Project Setup",
                ["Georef.Simple.Mode.NewProject.Description"] = "Use this when the model is still being set up. Survey Point becomes 0,0 in the selected CRS, and Project Base Point / internal origin uses either the entered X,Y offset or the southwest anchor derived from the selected PLATEAU grids.",
                ["Georef.Simple.Mode.Existing.Title"] = "Confirm Existing Setup",
                ["Georef.Simple.Mode.Existing.Description"] = "Use this when Survey Point and Project Base Point are already configured in Revit. The add-in will confirm them and save metadata without changing point geometry.",
                ["Georef.Simple.Section.SetupDetails"] = "Setup Details",
                ["Georef.Simple.Section.Preview"] = "Preview",
                ["Georef.Simple.Sidebar.PlannedSetup"] = "Planned Setup",
                ["Georef.Simple.PendingCrs"] = "Select a CRS to resolve the survey origin.",
                ["Georef.Simple.PendingOrigin"] = "CRS origin will be resolved after you choose a coordinate system.",
                ["Georef.Simple.PendingOffset"] = "Enter Project Base Point X/Y offsets.",
                ["Georef.Simple.CurrentOffsetUnavailable"] = "Current shared/project offset is not available.",
                ["Georef.Simple.ConfirmExisting.Label"] = "The detected Survey Point and Project Base Point setup is correct.",
                ["Georef.Simple.ConfirmExisting.Hint"] = "Confirm this only if the current Revit setup already matches the intended real-world relationship.",
                ["Georef.Simple.OverrideExisting.Label"] = "The detected setup is incorrect \u2014 configure manually",
                ["Georef.Simple.Validation.SelectCrs"] = "Select a coordinate reference system before continuing.",
                ["Georef.Simple.Validation.ConfirmExisting"] = "Confirm that the detected existing setup is correct before generating the preview.",
                ["Georef.Simple.Validation.SurveyUnavailable"] = "The current Survey Point could not be resolved into a geographic location.",
                ["Georef.Simple.Validation.ProjectBasePointUnavailable"] = "The current Project Base Point could not be resolved into shared/project coordinates and a geographic location.",
                ["Georef.Simple.Validation.OffsetX"] = "Enter a valid Project Base Point X / Easting offset in meters.",
                ["Georef.Simple.Validation.OffsetY"] = "Enter a valid Project Base Point Y / Northing offset in meters.",
                ["Georef.Simple.Planned.Mode"] = "Mode",
                ["Georef.Simple.Planned.Survey"] = "Survey Point",
                ["Georef.Simple.Planned.Project"] = "Project Base Point",
                ["Georef.Simple.Planned.Apply"] = "Apply",
                ["Georef.Simple.Planned.Apply.NewProject"] = "Set Survey Point to CRS origin and Project Base Point shared/project offset to the entered X,Y.",
                ["Georef.Simple.Planned.Apply.NewProject.Grid"] = "Set Survey Point to CRS origin and Project Base Point shared/project offset to the southwest corner derived from the selected PLATEAU grids.",
                ["Georef.Simple.Planned.Apply.Existing"] = "Keep the current Revit point geometry and save metadata from the detected setup.",
                ["Georef.Simple.Planned.Confirmation"] = "Confirmed",
                ["Georef.Simple.Preview.Mode"] = "Mode",
                ["Georef.Simple.Preview.Crs"] = "CRS",
                ["Georef.Simple.Preview.SurveyPoint"] = "Survey Point",
                ["Georef.Simple.Preview.ProjectBasePoint"] = "Project Base Point",
                ["Georef.Simple.Preview.Metadata"] = "Metadata",
                ["Georef.Simple.Preview.Metadata.Stored"] = "Stored metadata already exists",
                ["Georef.Simple.Preview.Metadata.Missing"] = "No stored metadata",
                ["Georef.Simple.Preview.Metadata.NewProject"] = "Create canonical metadata from the new-project setup",
                ["Georef.Simple.Preview.Metadata.Existing"] = "Create canonical metadata from the existing Revit setup",
                ["Georef.Simple.Preview.CurrentMode.Empty"] = "No saved setup yet",
                ["Georef.Simple.Preview.CurrentMode.Existing"] = "Existing Revit point setup",
                ["Georef.Simple.Preview.SurveyPoint.NewProject"] = "E 0.000 m, N 0.000 m / Lat {0:F6}, Lon {1:F6}",
                ["Georef.Simple.Preview.ProjectBasePoint.NewProject"] = "E {0:F3} m, N {1:F3} m",
                ["Georef.Simple.Preview.SurveyPoint.Existing"] = "Treat current Survey Point as CRS origin / E 0.000 m, N 0.000 m / Lat {0:F6}, Lon {1:F6}",
                ["Georef.Simple.Preview.ProjectBasePoint.Existing"] = "Keep current offset / E {0:F3} m, N {1:F3} m",
                ["Georef.Simple.Preview.NewProject.Change.Survey"] = "Survey Point will be positioned as the selected CRS origin for EPSG:{0}.",
                ["Georef.Simple.Preview.NewProject.Change.Project"] = "Project Base Point shared/project offset will resolve to E {0:F3} m, N {1:F3} m.",
                ["Georef.Simple.Preview.NewProject.Change.Metadata"] = "Canonical CRS metadata and the latest audit summary will be saved.",
                ["Georef.Simple.Preview.NewProject.NoChange.Geometry"] = "Model geometry will not be moved.",
                ["Georef.Simple.Preview.NewProject.NoChange.TrueNorth"] = "Current true north will be preserved.",
                ["Georef.Simple.Preview.NewProject.Persistence"] = "Applies a new-project CRS setup and saves canonical metadata plus a reusable Project Base Point reference.",
                ["Georef.Simple.Preview.NewProject.Impact"] = "This updates Revit project location data for a fresh setup but keeps the building geometry in place.",
                ["Georef.Simple.Preview.NewProject.Confidence"] = "Verified from an explicit CRS selection and explicit Project Base Point offset input.",
                ["Georef.Simple.Preview.Existing.Change.Metadata"] = "Canonical CRS metadata will be created from the current Revit point setup.",
                ["Georef.Simple.Preview.Existing.Change.WorkingPoint"] = "The current Project Base Point offset will be stored for downstream workflows.",
                ["Georef.Simple.Preview.Existing.NoChange.Survey"] = "Survey Point geometry will stay unchanged.",
                ["Georef.Simple.Preview.Existing.NoChange.Project"] = "Project Base Point and project location geometry will stay unchanged.",
                ["Georef.Simple.Preview.Existing.NoChange.TrueNorth"] = "Current true north will stay unchanged.",
                ["Georef.Simple.Preview.Existing.Persistence"] = "Saves canonical metadata and the current Project Base Point offset without re-shaping the model setup.",
                ["Georef.Simple.Preview.Existing.Impact"] = "This is a metadata-confirmation apply path for already-configured models.",
                ["Georef.Simple.Preview.Existing.Confidence"] = "Verified from the current Survey Point and Project Base Point state plus explicit user confirmation.",
                ["Georef.Simple.Preview.Warning.Overwrite"] = "Applying this setup will overwrite previously stored georeference metadata.",
                ["Georef.Simple.Preview.Warning.NonZeroSurvey"] = "The current Survey Point shared/project coordinates are not zero. Metadata will still treat the current Survey Point as the selected CRS origin.",
                ["Georef.Simple.SetupSource.NewProject"] = "New-project CRS origin plus Project Base Point offset setup",
                ["Georef.Simple.SetupSource.Existing"] = "Confirmed existing Survey Point and Project Base Point setup",
                ["Georef.Grid.InputModeLabel"] = "Project Base Point Input",
                ["Georef.Grid.Mode.Manual"] = "Manual Coordinates",
                ["Georef.Grid.Mode.Manual.Description"] = "Type explicit Easting / Northing values in the selected CRS.",
                ["Georef.Grid.Mode.Grid"] = "PLATEAU Grid Selection",
                ["Georef.Grid.Mode.Grid.Description"] = "Choose one or more nearby PLATEAU tertiary grids. The exact Project Base Point uses the southwest corner of the full selection.",
                ["Georef.Grid.Unavailable.NoHint"] = "PLATEAU grid selection is unavailable because the current project does not yet have a readable geographic hint. Use manual X/Y first, or establish a readable site or Project Base Point location.",
                ["Georef.Grid.Section.Title"] = "PLATEAU Grid Picker",
                ["Georef.Grid.Section.Description"] = "Select one or more nearby tertiary grids. The marker shows the exact southwest anchor that will be used for the Project Base Point.",
                ["Georef.Grid.List.Title"] = "Nearby Grids",
                ["Georef.Grid.List.Description"] = "Use the map or the list below. The full selection can be sparse; the southwest corner of the selection extent becomes the Project Base Point anchor.",
                ["Georef.Grid.Option.Primary"] = "Primary nearby grid from the current project hint.",
                ["Georef.Grid.Option.Neighbor"] = "Neighbor grid around the current project hint.",
                ["Georef.Grid.Validation.SelectGrid"] = "Select at least one PLATEAU grid before generating the preview.",
                ["Georef.Grid.Validation.ResolveSelection"] = "The selected PLATEAU grids could not be resolved into the chosen CRS.",
                ["Georef.Grid.PendingSelection"] = "Select one or more PLATEAU grids to derive the Project Base Point.",
                ["Georef.Grid.ProjectSummary.Projected"] = "SW corner of {0} selected grid(s) / E {1:F3} m, N {2:F3} m",
                ["Georef.Grid.ProjectSummary.Geographic"] = "SW corner of {0} selected grid(s) / Lat {1:F6}, Lon {2:F6}",
                ["Georef.Grid.Status.Select"] = "Seed: {0}. Select one or more nearby PLATEAU grids. The southwest corner of the full selection becomes the Project Base Point anchor.",
                ["Georef.Grid.Status.Selected.Projected"] = "{0} grid(s) selected. Exact Project Base Point anchor: E {1:F3} m, N {2:F3} m from the southwest corner of the selection.",
                ["Georef.Grid.Status.Selected.Geographic"] = "{0} grid(s) selected. Exact Project Base Point anchor: Lat {1:F6}, Lon {2:F6}. Select a CRS to resolve Easting / Northing.",
                ["Georef.Grid.Anchor.Pending"] = "No PLATEAU grid anchor selected yet.",
                ["Georef.Grid.Anchor.Resolved.Projected"] = "Exact apply point: southwest corner of {0} selected grid(s) / Lat {1:F6}, Lon {2:F6} / E {3:F3} m, N {4:F3} m",
                ["Georef.Grid.Anchor.Resolved.Geographic"] = "Exact apply point: southwest corner of {0} selected grid(s) / Lat {1:F6}, Lon {2:F6}",
                ["Georef.Grid.AnchorMarker"] = "Derived Project Base Point",
                ["Georef.Grid.SelectionLabel"] = "Selected PLATEAU Grids",
                ["Georef.Grid.SelectionMore"] = " + {0} more",
                ["Georef.Grid.Seed.ProjectBasePoint"] = "Current Project Base Point estimate",
                ["Georef.Grid.Seed.SiteLocation"] = "Current Revit site location",
                ["Georef.Grid.NoCandidates"] = "No nearby PLATEAU grids are available for the current project hint.",
                ["Georef.Grid.SetupSource.SelectionExtent"] = "Selected {0} PLATEAU tertiary grid(s); used southwest corner of selection extent",
                ["Georef.Current.Document"] = "Document",
                ["Georef.Current.StoredMetadata"] = "Stored Geo Metadata",
                ["Georef.Current.ReadOnly"] = "Read-Only",
                ["Georef.Current.SiteLocation"] = "Site Location",
                ["Georef.Current.SurveyShared"] = "Survey Point (shared)",
                ["Georef.Current.ProjectShared"] = "Project Base Point (shared)",
                ["Georef.Current.SurveyEstimate"] = "Survey Point Estimate",
                ["Georef.Current.ProjectEstimate"] = "Project Base Point Estimate",
                ["Georef.Current.TrueNorthAngle"] = "True North Angle",
                ["Plateau.Header"] = "Map-first import. Scan a package, click the exact grids you want, then preview and import only that filtered subset.",
                ["Plateau.Center.Package"] = "Package Scan",
                ["Plateau.Center.TileMap"] = "Detected Tile Map",
                ["Plateau.Center.Filters"] = "Import Filters",
                ["Plateau.Center.Preview"] = "Preview",
                ["Plateau.Sidebar.Reference"] = "Reference Context",
                ["Plateau.Sidebar.LastImport"] = "Last Import",
                ["Plateau.Sidebar.Warnings"] = "Warnings",
                ["Plateau.Sidebar.SourceFiles"] = "Detected Source Files",
                ["Mesh.Header"] = "Inspect the mesh around the active reference without changing canonical CRS or orientation facts.",
                ["Mesh.Center.Map"] = "Mesh Overlay",
                ["Mesh.Center.Neighbors"] = "Neighbor Meshes",
                ["Mesh.Sidebar.Reference"] = "Reference",
                ["Mesh.Sidebar.Details"] = "Mesh Details",
                ["Validation.Header"] = "Check readiness, blocking issues, and export health from one compact project dashboard.",
                ["Validation.Center.Health"] = "Project Health",
                ["Validation.Center.Findings"] = "Findings",
                ["Validation.Center.Readiness"] = "Export Readiness",
                ["Validation.Sidebar.Snapshot"] = "Shared Metadata Snapshot",
                ["Tiles.Header"] = "Prepare a lightweight viewer package, review the extracted scope, then export only when the summary looks correct.",
                ["Tiles.Center.Scope"] = "Export Scope",
                ["Tiles.Center.Prepared"] = "Prepared Export",
                ["Tiles.Center.Elements"] = "Prepared Elements",
                ["Tiles.Sidebar.Reference"] = "Reference Context",
                ["Tiles.Sidebar.LastExport"] = "Last Export",
                ["Tiles.Sidebar.Advanced"] = "Advanced Settings",
                ["City.Header"] = "Prepare a lightweight CityGML export from the selected 3D view, review validation, then write the package when the scope looks right.",
                ["City.Center.Scope"] = "Export Scope",
                ["City.Center.Prepared"] = "Prepared Export",
                ["City.Center.Validation"] = "Validation Messages",
                ["City.Center.Features"] = "Prepared Features",
                ["City.Sidebar.Reference"] = "Reference Context",
                ["City.Sidebar.LastExport"] = "Last Export",
                ["City.Sidebar.Advanced"] = "Advanced Options",
                ["Shell.RightPanel"] = "Context Panel",
                ["Plateau.PackageHint"] = "Choose the PLATEAU package root or source folder once, scan it, and keep the file-discovery details tucked away unless you need them.",
                ["Plateau.PackageAutoScanHint"] = "Select a PLATEAU package root when available. The scanner automatically uses the package's udx folder; otherwise it scans the selected folder directly.",
                ["Plateau.NoScan"] = "No folder has been scanned yet.",
                ["Plateau.TileMapHint"] = "The marker shows the active project reference. Click detected PLATEAU grid cells to toggle the exact import area, then use the synchronized checklist only if you want to fine-tune the selection.",
                ["Plateau.ShowModelOverlay"] = "Show Revit model overlay",
                ["Plateau.FiltersHint"] = "Pick the categories you actually need. The default interaction is the map; the cards below are the secondary review surface.",
                ["Plateau.NoFeatureTypes"] = "Scan a folder to populate category filters.",
                ["Plateau.TileSelectionSummary"] = "Tile Selection Summary",
                ["Plateau.TileSelectionHint"] = "The tile checklist stays synchronized with the map so you can review the exact selected area without losing context.",
                ["Plateau.TileSuggested"] = "Suggested from reference context",
                ["Plateau.NoTileOptions"] = "Scan a folder to populate tile selections.",
                ["Plateau.PreviewHint"] = "Load Preview resolves the filtered features into local Revit context shapes. Lightweight mode builds fast extrusions; detailed mode preserves the highest-LOD CityGML surfaces as faceted DirectShape geometry.",
                ["Plateau.GeometryModeLabel"] = "Geometry Mode",
                ["Plateau.NoPreview"] = "No preview is loaded yet.",
                ["Plateau.PreviewFeatures"] = "Preview Features",
                ["Plateau.PreviewFeaturesHint"] = "The preview list shows the filtered PLATEAU features that will become context shapes in Revit.",
                ["Plateau.NoFeatureNames"] = "Load a preview to inspect the filtered feature list before import.",
                ["Plateau.SuggestedTiles"] = "Suggested PLATEAU Tiles",
                ["Plateau.NoSuggestedTiles"] = "No tile candidates are available until the selected reference context can be resolved.",
                ["Plateau.NoLastImport"] = "No PLATEAU import has been recorded in module state yet.",
                ["Plateau.NoSourceFiles"] = "No detected source files are available until a package has been scanned.",
                ["Plateau.NoWarnings"] = "No warnings are recorded for the current scan or preview.",
                ["Mesh.ReferenceSource"] = "Reference Source",
                ["Mesh.MapHint"] = "The selected cell is highlighted on the shared map. Neighbor cells give quick context without forcing you to leave the mesh workflow.",
                ["Mesh.NoNeighbors"] = "Neighbor meshes are not available until the selected reference can be resolved.",
                ["Mesh.SaveHint"] = "Saving is only available when the reference source is Survey Point / Canonical Origin. Project Base Point mode stays read-only so the canonical mesh key remains stable.",
                ["Validation.FindingsHint"] = "Only the findings that matter are shown here. Each card is written as an issue with context instead of a raw report row.",
                ["Validation.NoFindings"] = "No validation findings were produced for the current shared geo state.",

                ["Georef.CurrentSetup.RefreshSurvey"] = "Refresh Current Survey Point",
                ["Georef.CurrentSetup.RefreshProject"] = "Refresh Current Project Base Point",
                ["Georef.CurrentSetup.Error.SelectCrs"] = "Select a coordinate reference system before reading the current Revit setup.",
                ["Georef.CurrentSetup.Hint.Standard"] = "Readable Survey Point or Project Base Point values from the current Revit project can be loaded as a draft for review. Click Apply to save the current target into this setup.",
                ["Georef.CurrentSetup.Hint.SplitSurvey"] = "Readable current Revit Survey Point values can be loaded as the shared split-workflow Survey draft. Click Apply to save that shared target into this setup.",
                ["Georef.CurrentSetup.Hint.SplitLocal"] = "Readable current Revit Project Base Point values can be loaded as the local split-workflow Project Base Point draft. Click Apply to save that local point into this setup.",
                ["Georef.CurrentSetup.ProjectNorthNote"] = "Project north remains the current model-axis reference; Revit V1 does not expose a separate standalone project north angle to store here.",
                ["Georef.CurrentSetup.Unavailable.Survey"] = "Current Revit Survey Point could not be converted. Make sure the project already has a readable site/project location setup.",
                ["Georef.CurrentSetup.Unavailable.Project"] = "Current Revit Project Base Point could not be converted. Make sure the project already has a readable site/project location setup.",
                ["Georef.CurrentSetup.Source.Survey"] = "Read from current Revit Survey Point and project location",
                ["Georef.CurrentSetup.Source.Project"] = "Read from current Revit Project Base Point and project location",
                ["Georef.CurrentSetup.Source.Working"] = "Read from current Revit Project Base Point and project location for Working Project Base Point",
                ["Georef.CurrentSetup.Verified"] = "Verified (read from current Revit setup)",
                ["Georef.SelectPointIntro.Standard"] = "Choose how to define the apply anchor, then use the map as the primary selection surface.",
                ["Georef.SelectPointIntro.Split"] = "Choose the far-away shared Survey target first, then confirm the local Project Base Point that should stay near the model.",
                ["Georef.Review.PrimaryTitle.Standard"] = "Primary Apply Anchor",
                ["Georef.Review.PrimaryTitle.Split"] = "Shared Survey Target",
                ["Georef.Review.PrimaryDescription.Standard"] = "Check the primary apply anchor first, then confirm the optional working Project Base Point only if you intend to reuse it in later workflows.",
                ["Georef.Review.PrimaryDescription.Split"] = "This point becomes the shared Survey / shared-coordinate target. It can be far away from the model because the actual Project Base Point stays local.",
                ["Georef.Review.WorkingTitle.Standard"] = "Working Project Base Point",
                ["Georef.Review.WorkingTitle.Split"] = "Local Project Base Point",
                ["Georef.Review.WorkingDescription.Standard"] = "This secondary reference is optional and is stored for later workflows. It does not replace the main apply anchor.",
                ["Georef.Review.WorkingDescription.Split"] = "This point is the local Project Base Point reference near the model. Split apply keeps the actual Revit Project Base Point local and aligns shared coordinates from it.",
                ["Georef.SetupIntent.PrimaryLabel.Standard"] = "Primary Anchor",
                ["Georef.SetupIntent.PrimaryLabel.Split"] = "Shared Survey Target",
                ["Georef.SetupIntent.WorkingLabel.Standard"] = "Working Project Base Point",
                ["Georef.SetupIntent.WorkingLabel.Split"] = "Local Project Base Point",
                ["Georef.SplitWorkflowSummary"] = "Split mode keeps the actual Revit Project Base Point near the model and uses the Survey Point/shared coordinates for the far-away real-world CRS target.",
                ["Georef.SelectedCaptureDescription.SplitWorking"] = "Capture or confirm the local Project Base Point near the model. Split apply keeps the actual Revit Project Base Point local and saves this same point for downstream PLATEAU and export workflows.",
                ["Georef.SelectedCaptureDescription.SplitShared"] = "Capture the shared Survey target in the selected CRS. This becomes the far-away shared-coordinate origin while the actual Revit Project Base Point stays local.",
                ["Georef.SelectedAnchorDescription.Split"] = "Split workflow always treats the primary captured point as the shared Survey target.",
                ["Georef.SelectedSiteDescription.SplitCurrentWorking"] = "Read the current actual Revit Project Base Point into the selected CRS and use it as the local split-workflow Project Base Point.",
                ["Georef.SelectedSiteDescription.SplitCurrentSurvey"] = "Read the current Survey Point/shared setup into the selected CRS and use it as the shared survey target.",
                ["Georef.Error.SelectCrsBeforeCoordinates"] = "Select a coordinate reference system before entering known coordinates.",
                ["Georef.Error.Preview.SelectCrs"] = "Select a coordinate reference system before generating a preview.",
                ["Georef.Error.Preview.SelectPoint"] = "Select a primary map point or enter known coordinates before generating a preview.",
                ["Georef.Error.Preview.SelectApplyMode"] = "Choose a setup intent before generating a preview.",

                ["Tiles.ScopeHint"] = "Choose whether to export the whole host model or a selected 3D view, decide which loaded links to include, and then pick the level of detail before preparing the bundle.",
                ["Tiles.ScopeMode"] = "Scope Mode",
                ["Tiles.ScopeWholeModel"] = "Whole Host Model",
                ["Tiles.ScopeSelectedView"] = "Selected 3D View",
                ["Tiles.VisibleExportView"] = "Visible Export View",
                ["Tiles.NoView"] = "No non-template 3D view is available in the current document.",
                ["Tiles.IncludeLinks"] = "Include Linked Revit Models",
                ["Tiles.IncludeLinksHint"] = "Checked linked models are exported with the selected scope. Whole Host Model exports full loaded links, while Selected 3D View follows host-view visibility.",
                ["Tiles.NoLinks"] = "No loaded Revit links were found. The export will use only the host model.",
                ["Tiles.LevelOfDetail"] = "Level Of Detail",
                ["Tiles.PreparedHint"] = "Prepare Export extracts model geometry, applies the chosen LOD, and packages the viewer-facing metadata before anything is written to disk.",
                ["Tiles.NoPrepared"] = "Prepare Export to inspect the bundle summary before writing files.",
                ["Tiles.ElementsHint"] = "This list previews the first prepared elements that will be written to the lightweight GLB package.",
                ["Tiles.NoElements"] = "No prepared element list is available until the export package has been prepared.",
                ["Tiles.NoLastExport"] = "No 3D Tiles export has been recorded in module state yet.",
                ["Tiles.OutputFolder"] = "Output Folder",
                ["Tiles.OutputHint"] = "The export writes tileset.json, content.glb, and levels.json into the selected folder. Object metadata in the GLB can be used for Cesium level filtering.",
                ["Tiles.PreciseCrs"] = "Precise CRS Projection",
                ["Tiles.PreciseCrsHint"] = "Rebases the tileset anchor to the building centroid using the real Transverse Mercator inverse (ProjNET). Eliminates the flat tangent-plane error that causes 1–3 m drift when the CRS zone origin is far from the building. Recommended when CRS-projected overlays such as shapefiles are loaded in Cesium.",
                ["Tiles.GeoidOffset"] = "Geoid Undulation N (m)",
                ["Tiles.GeoidOffsetHint"] = "Added to the orthometric/project-datum anchor elevation before computing the WGS84 ECEF transform: h = H + N. Use a positive value to lift the model. For central Japan (EPSG:6677) N ≈ +36 to +38 m. Look up the site-specific value at vldb.gsi.go.jp/sokuchi/surveycalc/geoidcalc. Leave 0 if the anchor elevation is already ellipsoidal.",
                ["City.ScopeHint"] = "Pick the 3D view, decide which loaded Revit links to include, and keep the scope intentionally narrow before preparing the export.",
                ["City.VisibleExportView"] = "Visible Export View",
                ["City.NoView"] = "No non-template 3D view is available in the current document.",
                ["City.IncludeLinks"] = "Include Linked Revit Models",
                ["City.IncludeLinksHint"] = "Checked linked models are exported together with the host model. Geometry still follows the selected host 3D view, so hidden links contribute nothing.",
                ["City.NoLinks"] = "No loaded Revit links were found. The export will use only the host model.",
                ["City.PreparedHint"] = "Prepare Export extracts geometry, resolves semantic mapping, and builds the lightweight CityGML package before anything is written to disk.",
                ["City.NoPrepared"] = "Prepare Export to inspect the summary before writing files.",
                ["City.ValidationHint"] = "Blocking validation errors keep export disabled. Warnings remain visible in the summary so the expected risk is obvious before you write files.",
                ["City.NoValidation"] = "No validation messages are available until the export package has been prepared.",
                ["City.FeaturesHint"] = "This preview list shows the first semantic features that will be written to the CityGML package.",
                ["City.NoFeatures"] = "No prepared feature list is available until the export package has been prepared.",
                ["City.NoLastExport"] = "No CityGML export has been recorded in module state yet.",
                ["City.TargetProfile"] = "Target Profile",
                ["City.CodelistOverrides"] = "Optional Codelist Overrides",
                ["City.CodelistHint"] = "Leave these blank to use the lightweight defaults. Fill them only when you already know the intended semantic code.",
                ["City.BuildingFunctionCode"] = "Building Function Code",
                ["City.RoadFunctionCode"] = "Road Function Code",
                ["City.VegetationFunctionCode"] = "Vegetation Function Code",
                ["City.OutputFolder"] = "Output Folder",
                ["City.OutputHint"] = "The export writes city-model.gml into the selected folder and keeps module-specific state separate from GeoProjectInfo.",

                ["Georef.Section.WorkflowSteps"] = "Workflow Steps",
                ["Georef.WorkflowMode"] = "Workflow Mode",
                ["Georef.V1Note"] = "V1 works with project location and true north. It does not rotate building geometry directly.",
                ["Georef.CaptureTarget"] = "Capture Target",
                ["Georef.SelectionMethod"] = "Selection Method",
                ["Georef.PrimaryAnchorTarget"] = "Primary Anchor Target",
                ["Georef.EastingMeters"] = "Easting (m)",
                ["Georef.NorthingMeters"] = "Northing (m)",
                ["Georef.KnownCoordinatesHint"] = "Enter normalized Easting / Northing in the selected CRS. For EPSG:6677, the natural origin is Easting 0, Northing 0.",
                ["Georef.WorkingPointSavedHint"] = "Working Project Base Point entries are saved as a secondary reference for later workflows.",
                ["Georef.SelectionDraft.Title"] = "Current Draft",
                ["Georef.Selection.AppliedTitle"] = "Saved In This Setup",
                ["Georef.SelectionDraft.None"] = "No pending selection for the current target. Capture a point, load the current Revit setup, or convert coordinates first.",
                ["Georef.Selection.Applied.None"] = "Not applied to this setup yet.",
                ["Georef.SelectionDraft.Hint.Ready"] = "This draft is not yet saved into the setup. Click Apply to keep it when you switch targets or continue.",
                ["Georef.SelectionDraft.Hint.Committed"] = "This target is already saved in the setup. New map or coordinate edits will not replace it until you click Apply again.",
                ["Georef.SelectionDraft.Hint.Empty"] = "Capture or load a point, then click Apply to save it into this setup.",
                ["Georef.Selection.ApplyPrimary"] = "Apply Primary Anchor",
                ["Georef.Selection.ApplyWorking"] = "Apply Working Project Base Point",
                ["Georef.MapSearchTooltip"] = "Search by Japanese place/address or paste latitude, longitude.",
                ["Georef.MapMarkerLegend"] = "Blue ring = Survey Point, amber ring = Project Base Point, and the red pin marks the current workflow selection.",
                ["Georef.Section.ReviewSelectedReferences"] = "Review Selected References",
                ["Georef.NoWorkingPointRun"] = "No working Project Base Point selected for this run.",
                ["Georef.AdvancedAlignPbp"] = "Advanced: Align Actual Project Base Point (Local Only)",
                ["Georef.AdvancedAlignPbpHint"] = "Use the captured Working Project Base Point to align the actual Revit Project Base Point only when the required local move stays within Revit's distance limit. Survey/shared coordinates stay fixed, and far-away targets should keep using the saved Working Project Base Point for later workflows.",
                ["Georef.AdvancedAlignPbpButton"] = "Align Actual Project Base Point...",
                ["Georef.Section.SetupIntent"] = "Setup Intent",
                ["Georef.SetupSourceNote"] = "Setup Source Note",
                ["Georef.SetupSourceNoteHint"] = "This note becomes the provenance summary for the apply step and stored metadata. In split mode it also documents why the actual Project Base Point stays local while the Survey Point carries the shared target.",
                ["Georef.TrueNorthAngleDegrees"] = "True North Angle (degrees)",
                ["Georef.TrueNorthAngleHint"] = "V1 adjusts the true north reference only. It does not rotate the model geometry itself.",
                ["Georef.Preview.Current"] = "Current",
                ["Georef.Preview.Proposed"] = "Proposed",
                ["Georef.Preview.WhatWillChange"] = "What Will Change",
                ["Georef.Preview.WhatWillNotChange"] = "What Will Not Change",
                ["Georef.Preview.PersistenceSummary"] = "Persistence Summary",
                ["Georef.Preview.ImpactSummary"] = "Impact Summary",
                ["Georef.Preview.ConfidenceProvenance"] = "Confidence / Provenance",
                ["Georef.NoWorkingPointYet"] = "No working Project Base Point selected yet.",
                ["Georef.Label.SelectedCrs"] = "Selected CRS",
                ["Georef.Action.ZoomWorkingProjectPoint"] = "Zoom To Working Project Base Point",
                ["Georef.SelectedCrsEmpty"] = "No CRS selected yet.",
                ["Georef.NotSelected"] = "Not selected",

                ["Georef.StepDescription.CurrentState"] = "Review the current project location status before any georeference workflow continues.",
                ["Georef.StepDescription.Crs.Standard"] = "Select the project CRS before choosing a primary anchor and an optional working Project Base Point.",
                ["Georef.StepDescription.Crs.Split"] = "Select the project CRS before defining the local Project Base Point and the far-away shared Survey target.",
                ["Georef.StepDescription.SiteReference.Standard"] = "Use the map, enter known Easting/Northing coordinates, or read the current Revit setup into the selected CRS to define the primary apply anchor and, if needed, a separate working Project Base Point.",
                ["Georef.StepDescription.SiteReference.Split"] = "Define the shared Survey target and the local Project Base Point separately. The actual Revit Project Base Point stays local while the Survey Point carries the far-away shared-coordinate target.",
                ["Georef.StepDescription.Review.Standard"] = "Review the selected geographic and projected coordinates that will feed the apply step and later working-coordinate workflows.",
                ["Georef.StepDescription.Review.Split"] = "Review the split local Project Base Point and shared Survey roles before choosing the Revit apply intent.",
                ["Georef.StepDescription.SetupIntent.Standard"] = "Choose what the apply step should change. The next screen is the final confirmation gate before any document modification.",
                ["Georef.StepDescription.SetupIntent.Split"] = "Split apply keeps the actual Revit Project Base Point local, updates shared/project location values from that local point, and repositions the Survey Point to the selected shared target.",
                ["Georef.StepDescription.Preview"] = "Review the current vs proposed state, then confirm before applying changes to the Revit document.",
                ["Georef.ApplyMode.MetadataOnly.Title"] = "Metadata Only",
                ["Georef.ApplyMode.MetadataOnly.Description"] = "Save canonical CRS, origin, confidence, and provenance without changing Revit project location values.",
                ["Georef.ApplyMode.ProjectLocation.Title"] = "Project Location",
                ["Georef.ApplyMode.ProjectLocation.Description"] = "Update Revit project location values from the selected point while keeping the current true north angle.",
                ["Georef.ApplyMode.ProjectLocationAngle.Title"] = "Project Location + True North",
                ["Georef.ApplyMode.ProjectLocationAngle.Description"] = "Update Revit project location values and true north. Building geometry is still not rotated.",
                ["Georef.SiteMode.Map.Title"] = "Map Point",
                ["Georef.SiteMode.Map.Description"] = "Pan, zoom, and click on the map to choose the approximate site reference.",
                ["Georef.SiteMode.Coordinates.Title"] = "Known CRS Coordinates",
                ["Georef.SiteMode.Coordinates.Description"] = "Enter explicit Easting/Northing values in the selected CRS and convert them into a geographic point for review.",
                ["Georef.SiteMode.Current.Title"] = "Current Revit Setup",
                ["Georef.SiteMode.Current.Description"] = "Read the current Revit Survey Point or Project Base Point, keep the current true north value, and convert that existing setup into the selected CRS.",
                ["Georef.AnchorTarget.Survey.Title"] = "Survey Point",
                ["Georef.AnchorTarget.Survey.Description"] = "Treat the primary CRS coordinates as the intended Survey Point location for the apply step.",
                ["Georef.AnchorTarget.Project.Title"] = "Project Base Point",
                ["Georef.AnchorTarget.Project.Description"] = "Treat the primary CRS coordinates as the intended Project Base Point location for the apply step.",
                ["Georef.CaptureTarget.Primary.Title"] = "Primary Apply Anchor",
                ["Georef.CaptureTarget.Primary.Description"] = "Capture the main point that the Revit apply step will use as its anchor.",
                ["Georef.CaptureTarget.Working.Title"] = "Working Project Base Point",
                ["Georef.CaptureTarget.Working.Description"] = "Capture an optional secondary Project Base Point reference for later import/export workflows.",
                ["Georef.QuickSetup.Title"] = "New Project Quick Setup",
                ["Georef.QuickSetup.Description"] = "For new projects: pick a CRS and enter projected coordinates. Sets both base points at the internal origin.",
                ["Georef.QuickSetup.StepTitle.CrsAndCoordinates"] = "CRS + Coordinates",
                ["Georef.QuickSetup.CoordinateHint"] = "Enter Easting / Northing in the selected CRS (EPSG:{0}). These coordinates define where Revit's internal origin sits in the real world.",
                ["Georef.QuickSetup.SelectCrsFirst"] = "Select a CRS above, then enter the projected coordinates for your project location.",
                ["Georef.QuickSetup.EastingLabel"] = "Easting (X) in meters",
                ["Georef.QuickSetup.NorthingLabel"] = "Northing (Y) in meters",
                ["Georef.QuickSetup.ApplyCoordinates"] = "Apply Coordinates",
                ["Georef.StepDescription.Crs.QuickSetup"] = "Select the project CRS and enter the projected coordinates for the project location.",

                ["Crs.Title"] = "Coordinate Reference System",
                ["Crs.SearchHint"] = "Search by EPSG code, zone, or place name.",
                ["Crs.Selected"] = "Selected CRS",
                ["Crs.SelectPrompt"] = "Select a CRS",
                ["Crs.Area"] = "Area",
                ["Crs.Units"] = "Units",
                ["Crs.Datum"] = "Datum",
                ["Crs.Zone"] = "Zone",
                ["Mesh.WindowTitle"] = "Mesh Inspector",
                ["Validation.WindowTitle"] = "Check Project",
                ["Tiles.WindowTitle"] = "3D Tiles Export",
                ["City.WindowTitle"] = "CityGML Export",
                ["Plateau.WindowTitle"] = "PLATEAU Context Import"
            },
            [UiLanguage.Japanese] = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["App.ProductTitle"] = "Revit Geo Suite",
                ["App.ShortTitle"] = "Geo Suite",
                ["Common.Back"] = "戻る",
                ["Common.Next"] = "次へ",
                ["Common.Close"] = "閉じる",
                ["Common.Apply"] = "適用",
                ["Common.Browse"] = "参照...",
                ["Common.Search"] = "検索",
                ["Common.Clear"] = "クリア",
                ["Common.LoadPreview"] = "プレビュー生成",
                ["Common.ImportContext"] = "コンテキスト取込",
                ["Common.PrepareExport"] = "書き出し準備",
                ["Common.Export3DTiles"] = "3D Tiles 書き出し",
                ["Common.ExportCityGml"] = "CityGML 書き出し",
                ["Common.CopyMesh"] = "メッシュをコピー",
                ["Common.SaveCanonicalMesh"] = "正規メッシュを保存",
                ["Common.ScanFolder"] = "フォルダをスキャン",
                ["Common.Preview"] = "プレビュー",
                ["Common.Yes"] = "はい",
                ["Common.No"] = "いいえ",
                ["Language.English"] = "EN",
                ["Language.Japanese"] = "日本語",
                ["Language.Label"] = "言語",
                ["Nav.Georeference"] = "GEO",
                ["Nav.PlateauImport"] = "PLT",
                ["Nav.MeshInspector"] = "MSH",
                ["Nav.Validation"] = "CHK",
                ["Nav.Tiles3DExport"] = "3DT",
                ["Nav.CityGmlExport"] = "GML",
                ["Module.Georeference"] = "ジオリファレンス",
                ["Module.PlateauImport"] = "PLATEAU取込",
                ["Module.MeshInspector"] = "メッシュ",
                ["Module.Validation"] = "検証",
                ["Module.Tiles3DExport"] = "3D Tiles",
                ["Module.CityGmlExport"] = "CityGML",
                ["Georef.Step.CurrentState"] = "現在状態",
                ["Georef.Step.Crs"] = "CRS",
                ["Georef.Step.SiteReference"] = "基準位置",
                ["Georef.Step.Review"] = "確認",
                ["Georef.Step.Intent"] = "設定内容",
                ["Georef.Step.Preview"] = "プレビュー",
                ["Georef.Sidebar.ProjectContext"] = "プロジェクト状況",
                ["Georef.Sidebar.PrimaryAnchor"] = "主アンカー",
                ["Georef.Sidebar.WorkingPoint"] = "作業用プロジェクト基点",
                ["Georef.Sidebar.Alerts"] = "注意事項",
                ["Georef.Section.StepperHint"] = "ガイドに沿って進めます。主作業だけを中央に表示し、補足情報は右パネルに集約します。",
                ["Georef.Section.MapContext"] = "検索・ズーム・マーカーで位置関係を確認しながら主アンカーと任意の作業点を設定できます。",
                ["Georef.Section.TechnicalDetails"] = "技術詳細",
                ["Georef.Action.ZoomSite"] = "サイト位置へズーム",
                ["Georef.Action.ZoomProjectPoint"] = "プロジェクト基点へズーム",
                ["Georef.Action.UseCoordinates"] = "座標を使用",
                ["Georef.Action.RefreshCurrent"] = "現在の測量点を更新",
                ["Georef.Action.ApplyManual"] = "適用は常に手動です。変更を確定する前にプレビューを確認してください。",
                ["Georef.Simple.Step.Setup"] = "CRS + 設定",
                ["Georef.Simple.StepDescription.NewProject"] = "プロジェクト CRS を選び、プロジェクト基点オフセットを入力するか近傍の PLATEAU グリッドを選択します。測量点は選択 CRS の原点として扱います。",
                ["Georef.Simple.StepDescription.Existing"] = "現在の測量点とプロジェクト基点の設定を確認し、その既存位置から正規メタデータを保存します。",
                ["Georef.Simple.Mode.NewProject.Title"] = "新規プロジェクト設定",
                ["Georef.Simple.Mode.NewProject.Description"] = "まだモデル設定中の新規プロジェクト向けです。測量点は選択 CRS の 0,0 となり、プロジェクト基点 / 内部原点は入力した X,Y オフセット、または選択した PLATEAU グリッド群から導いた南西アンカーを使います。",
                ["Georef.Simple.Mode.Existing.Title"] = "既存設定を確認",
                ["Georef.Simple.Mode.Existing.Description"] = "測量点とプロジェクト基点がすでに Revit で設定済みの場合に使います。点の形状は変えずに、その設定を確認してメタデータを保存します。",
                ["Georef.Simple.Section.SetupDetails"] = "設定詳細",
                ["Georef.Simple.Section.Preview"] = "プレビュー",
                ["Georef.Simple.Sidebar.PlannedSetup"] = "予定設定",
                ["Georef.Simple.PendingCrs"] = "測量点原点を解決するには CRS を選択してください。",
                ["Georef.Simple.PendingOrigin"] = "CRS を選ぶと原点が解決されます。",
                ["Georef.Simple.PendingOffset"] = "プロジェクト基点の X/Y オフセットを入力してください。",
                ["Georef.Simple.CurrentOffsetUnavailable"] = "現在の共有 / プロジェクトオフセットを取得できません。",
                ["Georef.Simple.ConfirmExisting.Label"] = "検出された測量点とプロジェクト基点の設定は正しいです。",
                ["Georef.Simple.ConfirmExisting.Hint"] = "現在の Revit 設定が意図した実世界の関係と一致している場合のみ確認してください。",
                ["Georef.Simple.OverrideExisting.Label"] = "検出された設定が正しくない \u2014 手動で設定する",
                ["Georef.Simple.Validation.SelectCrs"] = "続行する前に座標参照系を選択してください。",
                ["Georef.Simple.Validation.ConfirmExisting"] = "プレビューを生成する前に、検出された既存設定が正しいことを確認してください。",
                ["Georef.Simple.Validation.SurveyUnavailable"] = "現在の測量点を地理座標へ解決できませんでした。",
                ["Georef.Simple.Validation.ProjectBasePointUnavailable"] = "現在のプロジェクト基点を共有 / プロジェクト座標と地理座標へ解決できませんでした。",
                ["Georef.Simple.Validation.OffsetX"] = "有効なプロジェクト基点 X / Easting オフセット（メートル）を入力してください。",
                ["Georef.Simple.Validation.OffsetY"] = "有効なプロジェクト基点 Y / Northing オフセット（メートル）を入力してください。",
                ["Georef.Simple.Planned.Mode"] = "モード",
                ["Georef.Simple.Planned.Survey"] = "測量点",
                ["Georef.Simple.Planned.Project"] = "プロジェクト基点",
                ["Georef.Simple.Planned.Apply"] = "適用内容",
                ["Georef.Simple.Planned.Apply.NewProject"] = "測量点を CRS 原点にし、プロジェクト基点の共有 / プロジェクトオフセットを入力した X,Y に設定します。",
                ["Georef.Simple.Planned.Apply.NewProject.Grid"] = "測量点を CRS 原点にし、プロジェクト基点の共有 / プロジェクトオフセットを選択した PLATEAU グリッド範囲の南西隅に設定します。",
                ["Georef.Simple.Planned.Apply.Existing"] = "現在の Revit 点形状はそのままにし、検出した設定からメタデータを保存します。",
                ["Georef.Simple.Planned.Confirmation"] = "確認",
                ["Georef.Simple.Preview.Mode"] = "モード",
                ["Georef.Simple.Preview.Crs"] = "CRS",
                ["Georef.Simple.Preview.SurveyPoint"] = "測量点",
                ["Georef.Simple.Preview.ProjectBasePoint"] = "プロジェクト基点",
                ["Georef.Simple.Preview.Metadata"] = "メタデータ",
                ["Georef.Simple.Preview.Metadata.Stored"] = "保存済みメタデータあり",
                ["Georef.Simple.Preview.Metadata.Missing"] = "保存済みメタデータなし",
                ["Georef.Simple.Preview.Metadata.NewProject"] = "新規プロジェクト設定から正規メタデータを作成",
                ["Georef.Simple.Preview.Metadata.Existing"] = "既存 Revit 設定から正規メタデータを作成",
                ["Georef.Simple.Preview.CurrentMode.Empty"] = "まだ保存された設定はありません",
                ["Georef.Simple.Preview.CurrentMode.Existing"] = "既存の Revit 点設定",
                ["Georef.Simple.Preview.SurveyPoint.NewProject"] = "E 0.000 m, N 0.000 m / 緯度 {0:F6}, 経度 {1:F6}",
                ["Georef.Simple.Preview.ProjectBasePoint.NewProject"] = "E {0:F3} m, N {1:F3} m",
                ["Georef.Simple.Preview.SurveyPoint.Existing"] = "現在の測量点を CRS 原点として扱う / E 0.000 m, N 0.000 m / 緯度 {0:F6}, 経度 {1:F6}",
                ["Georef.Simple.Preview.ProjectBasePoint.Existing"] = "現在のオフセットを保持 / E {0:F3} m, N {1:F3} m",
                ["Georef.Simple.Preview.NewProject.Change.Survey"] = "測量点は EPSG:{0} の選択 CRS 原点として配置されます。",
                ["Georef.Simple.Preview.NewProject.Change.Project"] = "プロジェクト基点の共有 / プロジェクトオフセットは E {0:F3} m, N {1:F3} m に解決されます。",
                ["Georef.Simple.Preview.NewProject.Change.Metadata"] = "正規 CRS メタデータと最新の監査サマリを保存します。",
                ["Georef.Simple.Preview.NewProject.NoChange.Geometry"] = "モデルジオメトリ自体は移動しません。",
                ["Georef.Simple.Preview.NewProject.NoChange.TrueNorth"] = "現在の真北を維持します。",
                ["Georef.Simple.Preview.NewProject.Persistence"] = "新規プロジェクト向けの CRS 設定を適用し、正規メタデータと再利用可能なプロジェクト基点参照を保存します。",
                ["Georef.Simple.Preview.NewProject.Impact"] = "これは新規設定向けに Revit のプロジェクト位置データを更新しますが、建物ジオメトリはそのままです。",
                ["Georef.Simple.Preview.NewProject.Confidence"] = "明示的な CRS 選択と明示的なプロジェクト基点オフセット入力に基づく確認済み設定です。",
                ["Georef.Simple.Preview.Existing.Change.Metadata"] = "現在の Revit 点設定から正規 CRS メタデータを作成します。",
                ["Georef.Simple.Preview.Existing.Change.WorkingPoint"] = "現在のプロジェクト基点オフセットを後続ワークフロー用に保存します。",
                ["Georef.Simple.Preview.Existing.NoChange.Survey"] = "測量点の形状は変更しません。",
                ["Georef.Simple.Preview.Existing.NoChange.Project"] = "プロジェクト基点とプロジェクト位置の形状は変更しません。",
                ["Georef.Simple.Preview.Existing.NoChange.TrueNorth"] = "現在の真北は変更しません。",
                ["Georef.Simple.Preview.Existing.Persistence"] = "モデル設定を作り替えずに、正規メタデータと現在のプロジェクト基点オフセットを保存します。",
                ["Georef.Simple.Preview.Existing.Impact"] = "これは既存設定済みモデル向けのメタデータ確認適用パスです。",
                ["Georef.Simple.Preview.Existing.Confidence"] = "現在の測量点 / プロジェクト基点状態と明示的なユーザー確認に基づく確認済み設定です。",
                ["Georef.Simple.Preview.Warning.Overwrite"] = "この設定を適用すると、以前に保存されたジオリファレンスメタデータを上書きします。",
                ["Georef.Simple.Preview.Warning.NonZeroSurvey"] = "現在の測量点の共有 / プロジェクト座標は 0 ではありません。それでもメタデータでは現在の測量点を選択 CRS 原点として扱います。",
                ["Georef.Simple.SetupSource.NewProject"] = "新規プロジェクトの CRS 原点 + プロジェクト基点オフセット設定",
                ["Georef.Simple.SetupSource.Existing"] = "既存の測量点 / プロジェクト基点設定を確認",
                ["Georef.Grid.InputModeLabel"] = "プロジェクト基点入力",
                ["Georef.Grid.Mode.Manual"] = "手動座標",
                ["Georef.Grid.Mode.Manual.Description"] = "選択した CRS で Easting / Northing を直接入力します。",
                ["Georef.Grid.Mode.Grid"] = "PLATEAU グリッド選択",
                ["Georef.Grid.Mode.Grid.Description"] = "近傍の PLATEAU 三次メッシュを 1 つ以上選択します。実際のプロジェクト基点は、選択範囲全体の南西隅を使用します。",
                ["Georef.Grid.Unavailable.NoHint"] = "現在のプロジェクトから読める地理位置の手掛かりがないため、PLATEAU グリッド選択は利用できません。まず手動 X/Y を使うか、サイト位置またはプロジェクト基点の読める位置を用意してください。",
                ["Georef.Grid.Section.Title"] = "PLATEAU グリッドピッカー",
                ["Georef.Grid.Section.Description"] = "近傍の三次メッシュを 1 つ以上選択します。マーカーは、プロジェクト基点として実際に使われる正確な南西アンカーを示します。",
                ["Georef.Grid.List.Title"] = "近傍グリッド",
                ["Georef.Grid.List.Description"] = "地図または下の一覧を使って選択します。離れたグリッドを選んでもよく、選択範囲全体の南西隅がプロジェクト基点アンカーになります。",
                ["Georef.Grid.Option.Primary"] = "現在のプロジェクト手掛かりから得た主候補グリッドです。",
                ["Georef.Grid.Option.Neighbor"] = "現在のプロジェクト手掛かり周辺の近傍グリッドです。",
                ["Georef.Grid.Validation.SelectGrid"] = "プレビューを生成する前に、少なくとも 1 つの PLATEAU グリッドを選択してください。",
                ["Georef.Grid.Validation.ResolveSelection"] = "選択した PLATEAU グリッドを選択 CRS に解決できませんでした。",
                ["Georef.Grid.PendingSelection"] = "プロジェクト基点を導くために、1 つ以上の PLATEAU グリッドを選択してください。",
                ["Georef.Grid.ProjectSummary.Projected"] = "選択した {0} グリッドの南西隅 / E {1:F3} m, N {2:F3} m",
                ["Georef.Grid.ProjectSummary.Geographic"] = "選択した {0} グリッドの南西隅 / 緯度 {1:F6}, 経度 {2:F6}",
                ["Georef.Grid.Status.Select"] = "基準: {0}。近傍の PLATEAU グリッドを 1 つ以上選択してください。選択全体の南西隅がプロジェクト基点アンカーになります。",
                ["Georef.Grid.Status.Selected.Projected"] = "{0} グリッド選択中。正確なプロジェクト基点アンカー: E {1:F3} m, N {2:F3} m（選択範囲の南西隅）。",
                ["Georef.Grid.Status.Selected.Geographic"] = "{0} グリッド選択中。正確なプロジェクト基点アンカー: 緯度 {1:F6}, 経度 {2:F6}。Easting / Northing を解決するには CRS を選択してください。",
                ["Georef.Grid.Anchor.Pending"] = "まだ PLATEAU グリッドアンカーは選択されていません。",
                ["Georef.Grid.Anchor.Resolved.Projected"] = "実際に適用される点: 選択した {0} グリッドの南西隅 / 緯度 {1:F6}, 経度 {2:F6} / E {3:F3} m, N {4:F3} m",
                ["Georef.Grid.Anchor.Resolved.Geographic"] = "実際に適用される点: 選択した {0} グリッドの南西隅 / 緯度 {1:F6}, 経度 {2:F6}",
                ["Georef.Grid.AnchorMarker"] = "導出されたプロジェクト基点",
                ["Georef.Grid.SelectionLabel"] = "選択した PLATEAU グリッド",
                ["Georef.Grid.SelectionMore"] = " 他 {0}",
                ["Georef.Grid.Seed.ProjectBasePoint"] = "現在のプロジェクト基点推定位置",
                ["Georef.Grid.Seed.SiteLocation"] = "現在の Revit サイト位置",
                ["Georef.Grid.NoCandidates"] = "現在のプロジェクト手掛かりに対して近傍の PLATEAU グリッドがありません。",
                ["Georef.Grid.SetupSource.SelectionExtent"] = "{0} 個の PLATEAU 三次メッシュを選択し、その選択範囲の南西隅を使用",
                ["Georef.Current.Document"] = "ドキュメント",
                ["Georef.Current.StoredMetadata"] = "保存済みジオメタデータ",
                ["Georef.Current.ReadOnly"] = "読み取り専用",
                ["Georef.Current.SiteLocation"] = "サイト位置",
                ["Georef.Current.SurveyShared"] = "測量点（共有）",
                ["Georef.Current.ProjectShared"] = "プロジェクト基点（共有）",
                ["Georef.Current.SurveyEstimate"] = "測量点推定",
                ["Georef.Current.ProjectEstimate"] = "プロジェクト基点推定",
                ["Georef.Current.TrueNorthAngle"] = "真北角度",
                ["Plateau.Header"] = "地図中心の取込です。パッケージを読み込み、必要なグリッドだけをクリックして選択し、絞り込んだ内容だけを取り込みます。",
                ["Plateau.Center.Package"] = "パッケージ読込",
                ["Plateau.Center.TileMap"] = "検出グリッド地図",
                ["Plateau.Center.Filters"] = "取込フィルタ",
                ["Plateau.Center.Preview"] = "プレビュー",
                ["Plateau.Sidebar.Reference"] = "参照コンテキスト",
                ["Plateau.Sidebar.LastImport"] = "前回の取込",
                ["Plateau.Sidebar.Warnings"] = "警告",
                ["Plateau.Sidebar.SourceFiles"] = "検出ソースファイル",
                ["Mesh.Header"] = "基準点まわりのメッシュを確認します。正規CRSや方位の事実は変更しません。",
                ["Mesh.Center.Map"] = "メッシュ重ね表示",
                ["Mesh.Center.Neighbors"] = "周辺メッシュ",
                ["Mesh.Sidebar.Reference"] = "参照元",
                ["Mesh.Sidebar.Details"] = "メッシュ詳細",
                ["Validation.Header"] = "準備状況、要対応事項、書き出し readiness を1つのダッシュボードで確認します。",
                ["Validation.Center.Health"] = "プロジェクト健全性",
                ["Validation.Center.Findings"] = "検出結果",
                ["Validation.Center.Readiness"] = "書き出し準備状況",
                ["Validation.Sidebar.Snapshot"] = "共有メタデータのスナップショット",
                ["Tiles.Header"] = "軽量ビューア用パッケージを準備し、内容を確認してから3D Tilesを書き出します。",
                ["Tiles.Center.Scope"] = "書き出し範囲",
                ["Tiles.Center.Prepared"] = "準備済み書き出し",
                ["Tiles.Center.Elements"] = "準備済み要素",
                ["Tiles.Sidebar.Reference"] = "参照コンテキスト",
                ["Tiles.Sidebar.LastExport"] = "前回の書き出し",
                ["Tiles.Sidebar.Advanced"] = "詳細設定",
                ["City.Header"] = "選択した3Dビューから軽量CityGMLを書き出します。検証内容を確認してから保存します。",
                ["City.Center.Scope"] = "書き出し範囲",
                ["City.Center.Prepared"] = "準備済み書き出し",
                ["City.Center.Validation"] = "検証メッセージ",
                ["City.Center.Features"] = "準備済みフィーチャ",
                ["City.Sidebar.Reference"] = "参照コンテキスト",
                ["City.Sidebar.LastExport"] = "前回の書き出し",
                ["City.Sidebar.Advanced"] = "詳細オプション",
                ["Shell.RightPanel"] = "コンテキストパネル",
                ["Plateau.PackageHint"] = "PLATEAU パッケージルートまたはソースフォルダを一度選択してスキャンし、必要なとき以外はファイル検出の詳細を閉じておけます。",
                ["Plateau.PackageAutoScanHint"] = "可能であれば PLATEAU パッケージルートを選択してください。スキャナは自動的にそのパッケージの udx フォルダを使い、なければ選択フォルダを直接スキャンします。",
                ["Plateau.NoScan"] = "まだフォルダはスキャンされていません。",
                ["Plateau.TileMapHint"] = "マーカーは現在のプロジェクト参照を示します。検出された PLATEAU グリッドセルをクリックして取込範囲を切り替え、必要な場合のみ同期チェックリストで微調整します。",
                ["Plateau.ShowModelOverlay"] = "Revit モデルオーバーレイを表示",
                ["Plateau.FiltersHint"] = "本当に必要なカテゴリだけを選択します。既定の操作面は地図で、下のカードは補助的な確認面です。",
                ["Plateau.NoFeatureTypes"] = "カテゴリフィルタを表示するにはフォルダをスキャンしてください。",
                ["Plateau.TileSelectionSummary"] = "タイル選択サマリ",
                ["Plateau.TileSelectionHint"] = "タイルのチェックリストは地図と同期しているため、位置関係を失わずに選択範囲を確認できます。",
                ["Plateau.TileSuggested"] = "参照コンテキストから推奨",
                ["Plateau.NoTileOptions"] = "タイル選択を表示するにはフォルダをスキャンしてください。",
                ["Plateau.PreviewHint"] = "プレビュー生成では、絞り込んだフィーチャを Revit ローカル文脈の形状へ変換します。軽量モードは高速な押し出しを作成し、詳細モードは最高LODの CityGML 面をファセット DirectShape として保持します。",
                ["Plateau.GeometryModeLabel"] = "ジオメトリモード",
                ["Plateau.NoPreview"] = "まだプレビューは生成されていません。",
                ["Plateau.PreviewFeatures"] = "プレビュー対象フィーチャ",
                ["Plateau.PreviewFeaturesHint"] = "この一覧は、Revit でコンテキスト形状になる絞り込み済みの PLATEAU フィーチャを示します。",
                ["Plateau.NoFeatureNames"] = "取込前に絞り込み済みフィーチャ一覧を確認するにはプレビューを生成してください。",
                ["Plateau.SuggestedTiles"] = "推奨 PLATEAU タイル",
                ["Plateau.NoSuggestedTiles"] = "選択中の参照コンテキストを解決できるまで、タイル候補は表示されません。",
                ["Plateau.NoLastImport"] = "モジュール状態に PLATEAU 取込履歴はまだ記録されていません。",
                ["Plateau.NoSourceFiles"] = "パッケージをスキャンするまで、検出ソースファイルは表示されません。",
                ["Plateau.NoWarnings"] = "現在のスキャンまたはプレビューに警告はありません。",
                ["Mesh.ReferenceSource"] = "参照元",
                ["Mesh.MapHint"] = "選択したセルは共通地図上で強調表示されます。周辺セルも同時に見えるので、メッシュワークフローを離れずに位置関係を把握できます。",
                ["Mesh.NoNeighbors"] = "選択中の参照を解決できるまで、周辺メッシュは表示されません。",
                ["Mesh.SaveHint"] = "保存できるのは参照元が測量点 / 正規原点の場合のみです。プロジェクト基点モードは読み取り専用のままにして、正規メッシュキーの安定性を保ちます。",
                ["Validation.FindingsHint"] = "ここには重要な検出結果だけを表示します。各カードは生のレポート行ではなく、背景付きの課題として示されます。",
                ["Validation.NoFindings"] = "現在の共有ジオ状態では検出結果はありません。",

                ["Georef.CurrentSetup.RefreshSurvey"] = "現在の測量点を更新",
                ["Georef.CurrentSetup.RefreshProject"] = "現在のプロジェクト基点を更新",
                ["Georef.CurrentSetup.Error.SelectCrs"] = "現在の Revit 設定を読み込む前に座標参照系を選択してください。",
                ["Georef.CurrentSetup.Hint.Standard"] = "現在の Revit プロジェクトから読み取れる測量点またはプロジェクト基点の値は確認用ドラフトとして読み込めます。現在の対象をこの設定に保存するには適用を押してください。",
                ["Georef.CurrentSetup.Hint.SplitSurvey"] = "現在の Revit 測量点の値は、分離ワークフローの共有測量ドラフトとして読み込めます。この設定に共有ターゲットを保存するには適用を押してください。",
                ["Georef.CurrentSetup.Hint.SplitLocal"] = "現在の Revit プロジェクト基点の値は、分離ワークフローのローカルプロジェクト基点ドラフトとして読み込めます。この設定にローカル点を保存するには適用を押してください。",
                ["Georef.CurrentSetup.ProjectNorthNote"] = "プロジェクト北は現在のモデル軸参照のままです。Revit V1 では独立したプロジェクト北角度をここに保存できません。",
                ["Georef.CurrentSetup.Unavailable.Survey"] = "現在の Revit 測量点を変換できませんでした。プロジェクトに読み取り可能なサイト／プロジェクト位置設定があることを確認してください。",
                ["Georef.CurrentSetup.Unavailable.Project"] = "現在の Revit プロジェクト基点を変換できませんでした。プロジェクトに読み取り可能なサイト／プロジェクト位置設定があることを確認してください。",
                ["Georef.CurrentSetup.Source.Survey"] = "現在の Revit 測量点とプロジェクト位置から読み取り",
                ["Georef.CurrentSetup.Source.Project"] = "現在の Revit プロジェクト基点とプロジェクト位置から読み取り",
                ["Georef.CurrentSetup.Source.Working"] = "作業用プロジェクト基点として現在の Revit プロジェクト基点とプロジェクト位置から読み取り",
                ["Georef.CurrentSetup.Verified"] = "確認済み（現在の Revit 設定から読み取り）",
                ["Georef.SelectPointIntro.Standard"] = "適用アンカーの定義方法を選び、主な選択面として地図を使います。",
                ["Georef.SelectPointIntro.Split"] = "まず遠距離の共有測量ターゲットを選び、その後モデル近傍に残すローカルなプロジェクト基点を確認します。",
                ["Georef.Review.PrimaryTitle.Standard"] = "主適用アンカー",
                ["Georef.Review.PrimaryTitle.Split"] = "共有測量ターゲット",
                ["Georef.Review.PrimaryDescription.Standard"] = "まず主適用アンカーを確認し、その後、後続ワークフローで再利用する予定がある場合のみ任意の作業用プロジェクト基点を確認します。",
                ["Georef.Review.PrimaryDescription.Split"] = "この点は共有の測量点／共有座標ターゲットになります。実際のプロジェクト基点はローカルに留まるため、モデルから離れた位置でも設定できます。",
                ["Georef.Review.WorkingTitle.Standard"] = "作業用プロジェクト基点",
                ["Georef.Review.WorkingTitle.Split"] = "ローカルプロジェクト基点",
                ["Georef.Review.WorkingDescription.Standard"] = "この副次参照は任意で、後続ワークフロー用に保存されます。主適用アンカーの代わりにはなりません。",
                ["Georef.Review.WorkingDescription.Split"] = "この点はモデル近傍のローカルなプロジェクト基点参照です。分離適用では、実際の Revit プロジェクト基点をローカルに保ちつつ、ここから共有座標を整合させます。",
                ["Georef.SetupIntent.PrimaryLabel.Standard"] = "主アンカー",
                ["Georef.SetupIntent.PrimaryLabel.Split"] = "共有測量ターゲット",
                ["Georef.SetupIntent.WorkingLabel.Standard"] = "作業用プロジェクト基点",
                ["Georef.SetupIntent.WorkingLabel.Split"] = "ローカルプロジェクト基点",
                ["Georef.SplitWorkflowSummary"] = "分離モードでは、実際の Revit プロジェクト基点をモデル近傍に保ち、測量点／共有座標で遠距離の実世界 CRS ターゲットを表現します。",
                ["Georef.SelectedCaptureDescription.SplitWorking"] = "モデル近傍のローカルなプロジェクト基点を取得または確認します。分離適用では、実際の Revit プロジェクト基点をローカルに保ち、この同じ点を後続の PLATEAU と書き出しワークフロー用にも保存します。",
                ["Georef.SelectedCaptureDescription.SplitShared"] = "選択した CRS で共有測量ターゲットを取得します。これは遠距離の共有座標原点となり、実際の Revit プロジェクト基点はローカルに保たれます。",
                ["Georef.SelectedAnchorDescription.Split"] = "分離ワークフローでは、主取得点は常に共有測量ターゲットとして扱われます。",
                ["Georef.SelectedSiteDescription.SplitCurrentWorking"] = "現在の実際の Revit プロジェクト基点を選択CRSに読み込み、分離ワークフローのローカルプロジェクト基点として使います。",
                ["Georef.SelectedSiteDescription.SplitCurrentSurvey"] = "現在の測量点／共有設定を選択CRSに読み込み、共有測量ターゲットとして使います。",
                ["Georef.Error.SelectCrsBeforeCoordinates"] = "既知座標を入力する前に座標参照系を選択してください。",
                ["Georef.Error.Preview.SelectCrs"] = "プレビューを生成する前に座標参照系を選択してください。",
                ["Georef.Error.Preview.SelectPoint"] = "プレビューを生成する前に主地図点を選択するか既知座標を入力してください。",
                ["Georef.Error.Preview.SelectApplyMode"] = "プレビューを生成する前に設定内容を選択してください。",

                ["Tiles.ScopeHint"] = "ホストモデル全体または選択した 3D ビューのどちらを対象にするかを決め、含める読み込み済み Revit リンクを選び、詳細レベルを選択してからバンドルを準備します。",
                ["Tiles.ScopeMode"] = "範囲モード",
                ["Tiles.ScopeWholeModel"] = "ホストモデル全体",
                ["Tiles.ScopeSelectedView"] = "選択した 3D ビュー",
                ["Tiles.VisibleExportView"] = "表示対象の書き出しビュー",
                ["Tiles.NoView"] = "現在のドキュメントにはテンプレートではない 3D ビューがありません。",
                ["Tiles.IncludeLinks"] = "読み込み済み Revit リンクを含める",
                ["Tiles.IncludeLinksHint"] = "チェックしたリンクモデルは選択した範囲と一緒に書き出されます。ホストモデル全体では読み込み済みリンク全体を、選択した 3D ビューではホストビューの表示状態に従ったジオメトリを書き出します。",
                ["Tiles.NoLinks"] = "読み込み済みの Revit リンクは見つかりませんでした。書き出しはホストモデルのみを使用します。",
                ["Tiles.LevelOfDetail"] = "詳細レベル",
                ["Tiles.PreparedHint"] = "書き出し準備では、モデルジオメトリを抽出し、選択した LOD を適用し、ディスクに書き込む前にビューア向けメタデータをまとめます。",
                ["Tiles.NoPrepared"] = "ファイルを書き出す前に、書き出し準備を実行してバンドル概要を確認してください。",
                ["Tiles.ElementsHint"] = "この一覧は、軽量 GLB パッケージへ書き出される最初の準備済み要素をプレビューします。",
                ["Tiles.NoElements"] = "書き出しパッケージの準備が完了するまで、準備済み要素一覧は表示されません。",
                ["Tiles.NoLastExport"] = "モジュール状態に 3D Tiles 書き出し履歴はまだ記録されていません。",
                ["Tiles.OutputFolder"] = "出力フォルダ",
                ["Tiles.OutputHint"] = "書き出しでは、選択したフォルダに tileset.json、content.glb、levels.json を出力します。GLB 内のオブジェクトメタデータを Cesium の階層フィルタに利用できます。",
                ["Tiles.PreciseCrs"] = "正確なCRS投影",
                ["Tiles.PreciseCrsHint"] = "ProjNET の真横メルカトル逆変換を使って、タイルセットのアンカーを建物の重心に再基準化します。CRS ゾーン原点が建物から離れている場合に生じる 1〜3 m のフラット接平面誤差を解消します。シェープファイルなど CRS 投影オーバーレイを Cesium に読み込む場合に推奨されます。",
                ["Tiles.GeoidOffset"] = "ジオイド高 N (m)",
                ["Tiles.GeoidOffsetHint"] = "WGS84 ECEF 変換を行う前に、標高またはプロジェクト基準高のアンカー標高へ加算します: h = H + N。正の値でモデルを上げます。日本中部（EPSG:6677）では N ≈ +36〜+38 m が目安です。地点ごとの値は vldb.gsi.go.jp/sokuchi/surveycalc/geoidcalc で確認できます。アンカー標高がすでに楕円体高の場合は 0 のままにしてください。",
                ["City.ScopeHint"] = "3D ビューを選び、含める読み込み済み Revit リンクを決め、書き出し準備前に対象範囲を意図的に絞ります。",
                ["City.VisibleExportView"] = "表示対象の書き出しビュー",
                ["City.NoView"] = "現在のドキュメントにはテンプレートではない 3D ビューがありません。",
                ["City.IncludeLinks"] = "読み込み済み Revit リンクを含める",
                ["City.IncludeLinksHint"] = "チェックしたリンクモデルはホストモデルと一緒に書き出されます。ジオメトリは選択したホスト 3D ビューに従うため、非表示リンクは何も寄与しません。",
                ["City.NoLinks"] = "読み込み済みの Revit リンクは見つかりませんでした。書き出しはホストモデルのみを使用します。",
                ["City.PreparedHint"] = "書き出し準備では、ジオメトリを抽出し、セマンティック対応付けを解決し、ディスクに書き込む前に軽量 CityGML パッケージを構築します。",
                ["City.NoPrepared"] = "ファイルを書き出す前に、書き出し準備を実行してサマリを確認してください。",
                ["City.ValidationHint"] = "検証エラーがあると書き出しは無効になります。警告はサマリに残るため、書き込む前に想定リスクを把握できます。",
                ["City.NoValidation"] = "書き出しパッケージの準備が完了するまで、検証メッセージは表示されません。",
                ["City.FeaturesHint"] = "このプレビュー一覧は、CityGML パッケージへ書き出される最初のセマンティックフィーチャを示します。",
                ["City.NoFeatures"] = "書き出しパッケージの準備が完了するまで、準備済みフィーチャ一覧は表示されません。",
                ["City.NoLastExport"] = "モジュール状態に CityGML 書き出し履歴はまだ記録されていません。",
                ["City.TargetProfile"] = "ターゲットプロファイル",
                ["City.CodelistOverrides"] = "任意のコードリスト上書き",
                ["City.CodelistHint"] = "軽量既定値を使う場合は空欄のままにします。意図するセマンティックコードが分かっている場合のみ入力してください。",
                ["City.BuildingFunctionCode"] = "建物機能コード",
                ["City.RoadFunctionCode"] = "道路機能コード",
                ["City.VegetationFunctionCode"] = "植生機能コード",
                ["City.OutputFolder"] = "出力フォルダ",
                ["City.OutputHint"] = "書き出しでは、選択したフォルダに city-model.gml を出力し、GeoProjectInfo とは別にモジュール固有状態を保持します。",

                ["Georef.Section.WorkflowSteps"] = "ワークフローステップ",
                ["Georef.WorkflowMode"] = "ワークフローモード",
                ["Georef.V1Note"] = "V1ではプロジェクト位置と真北を扱います。建物ジオメトリ自体は回転しません。",
                ["Georef.CaptureTarget"] = "取得対象",
                ["Georef.SelectionMethod"] = "選択方法",
                ["Georef.PrimaryAnchorTarget"] = "主アンカー対象",
                ["Georef.EastingMeters"] = "Easting (m)",
                ["Georef.NorthingMeters"] = "Northing (m)",
                ["Georef.KnownCoordinatesHint"] = "選択したCRSで正規化された Easting / Northing を入力します。EPSG:6677 では自然原点が Easting 0、Northing 0 です。",
                ["Georef.WorkingPointSavedHint"] = "作業用プロジェクト基点は後続ワークフロー用の副次参照として保存されます。",
                ["Georef.SelectionDraft.Title"] = "現在のドラフト",
                ["Georef.Selection.AppliedTitle"] = "この設定に保存済み",
                ["Georef.SelectionDraft.None"] = "現在の対象に対する保留中の選択はありません。点を取得するか、現在の Revit 設定を読み込むか、座標を変換してください。",
                ["Georef.Selection.Applied.None"] = "まだこの設定には適用されていません。",
                ["Georef.SelectionDraft.Hint.Ready"] = "このドラフトはまだ設定に保存されていません。対象を切り替えたり先へ進む前に適用を押してください。",
                ["Georef.SelectionDraft.Hint.Committed"] = "この対象はすでに設定へ保存されています。地図や座標の新しい編集は、もう一度適用を押すまで置き換わりません。",
                ["Georef.SelectionDraft.Hint.Empty"] = "点を取得または読み込んでから、適用を押してこの設定へ保存してください。",
                ["Georef.Selection.ApplyPrimary"] = "主アンカーを適用",
                ["Georef.Selection.ApplyWorking"] = "作業用プロジェクト基点を適用",
                ["Georef.MapSearchTooltip"] = "日本の地名・住所で検索するか、緯度経度を貼り付けます。",
                ["Georef.MapMarkerLegend"] = "青リング = 測量点、琥珀リング = プロジェクト基点、赤ピン = 現在のワークフロー選択です。",
                ["Georef.Section.ReviewSelectedReferences"] = "選択した参照を確認",
                ["Georef.NoWorkingPointRun"] = "この実行では作業用プロジェクト基点が選択されていません。",
                ["Georef.AdvancedAlignPbp"] = "詳細: 実際のプロジェクト基点を整列（ローカルのみ）",
                ["Georef.AdvancedAlignPbpHint"] = "取得済みの作業用プロジェクト基点を使って、必要なローカル移動が Revit の距離制限内に収まる場合にのみ、実際の Revit プロジェクト基点を整列します。測量点／共有座標は固定のままで、遠距離ターゲットは後続ワークフロー用に保存された作業用プロジェクト基点を使い続けてください。",
                ["Georef.AdvancedAlignPbpButton"] = "実際のプロジェクト基点を整列...",
                ["Georef.Section.SetupIntent"] = "設定内容",
                ["Georef.SetupSourceNote"] = "設定ソースメモ",
                ["Georef.SetupSourceNoteHint"] = "このメモは適用時と保存メタデータの由来サマリになります。分離モードでは、実際のプロジェクト基点をローカルに保ち、測量点が共有ターゲットを担う理由も記録します。",
                ["Georef.TrueNorthAngleDegrees"] = "真北角度（度）",
                ["Georef.TrueNorthAngleHint"] = "V1 は真北参照のみを調整します。モデルジオメトリ自体は回転しません。",
                ["Georef.Preview.Current"] = "現在",
                ["Georef.Preview.Proposed"] = "変更後",
                ["Georef.Preview.WhatWillChange"] = "変更される内容",
                ["Georef.Preview.WhatWillNotChange"] = "変更されない内容",
                ["Georef.Preview.PersistenceSummary"] = "保存内容サマリ",
                ["Georef.Preview.ImpactSummary"] = "影響サマリ",
                ["Georef.Preview.ConfidenceProvenance"] = "確度 / 由来",
                ["Georef.NoWorkingPointYet"] = "作業用プロジェクト基点はまだ選択されていません。",
                ["Georef.Label.SelectedCrs"] = "選択したCRS",
                ["Georef.Action.ZoomWorkingProjectPoint"] = "作業用プロジェクト基点へズーム",
                ["Georef.SelectedCrsEmpty"] = "CRSはまだ選択されていません。",
                ["Georef.NotSelected"] = "未選択",

                ["Georef.StepDescription.CurrentState"] = "ジオリファレンスの処理を始める前に、現在のプロジェクト位置状態を確認します。",
                ["Georef.StepDescription.Crs.Standard"] = "主アンカーと任意の作業用プロジェクト基点を選ぶ前に、プロジェクトCRSを選択します。",
                ["Georef.StepDescription.Crs.Split"] = "ローカルなプロジェクト基点と遠距離の共有測量ターゲットを定義する前に、プロジェクトCRSを選択します。",
                ["Georef.StepDescription.SiteReference.Standard"] = "地図、既知の Easting/Northing 座標、または現在の Revit 設定を選択CRSに読み込んで、主適用アンカーと必要なら別の作業用プロジェクト基点を定義します。",
                ["Georef.StepDescription.SiteReference.Split"] = "共有の測量ターゲットとローカルなプロジェクト基点を分けて定義します。実際の Revit プロジェクト基点はローカルに残し、測量点が遠距離の共有座標ターゲットを担います。",
                ["Georef.StepDescription.Review.Standard"] = "適用ステップと後続の作業座標ワークフローで使う地理座標・投影座標を確認します。",
                ["Georef.StepDescription.Review.Split"] = "ローカルなプロジェクト基点と共有測量ターゲットの役割分担を、Revit への適用内容を選ぶ前に確認します。",
                ["Georef.StepDescription.SetupIntent.Standard"] = "適用ステップで何を変更するかを選びます。次の画面が実際にドキュメントを変更する前の最終確認です。",
                ["Georef.StepDescription.SetupIntent.Split"] = "分離適用では、実際の Revit プロジェクト基点をローカルに保ち、そのローカル点から共有／プロジェクト位置を更新し、測量点を選択した共有ターゲットへ再配置します。",
                ["Georef.StepDescription.Preview"] = "現在状態と変更後状態を確認してから、Revit ドキュメントへ適用します。",
                ["Georef.ApplyMode.MetadataOnly.Title"] = "メタデータのみ",
                ["Georef.ApplyMode.MetadataOnly.Description"] = "Revit のプロジェクト位置値は変更せず、正規のCRS、原点、確度、由来のみを保存します。",
                ["Georef.ApplyMode.ProjectLocation.Title"] = "プロジェクト位置",
                ["Georef.ApplyMode.ProjectLocation.Description"] = "現在の真北角度を維持したまま、選択した点から Revit のプロジェクト位置値を更新します。",
                ["Georef.ApplyMode.ProjectLocationAngle.Title"] = "プロジェクト位置 + 真北",
                ["Georef.ApplyMode.ProjectLocationAngle.Description"] = "Revit のプロジェクト位置値と真北を更新します。建物ジオメトリ自体は回転しません。",
                ["Georef.SiteMode.Map.Title"] = "地図上の点",
                ["Georef.SiteMode.Map.Description"] = "地図をパン・ズームしてクリックし、おおよその基準位置を選択します。",
                ["Georef.SiteMode.Coordinates.Title"] = "既知のCRS座標",
                ["Georef.SiteMode.Coordinates.Description"] = "選択したCRSの Easting/Northing を明示的に入力し、確認用の地理点へ変換します。",
                ["Georef.SiteMode.Current.Title"] = "現在の Revit 設定",
                ["Georef.SiteMode.Current.Description"] = "現在の Revit の測量点またはプロジェクト基点を読み取り、真北を保持したまま選択CRSへ変換します。",
                ["Georef.AnchorTarget.Survey.Title"] = "測量点",
                ["Georef.AnchorTarget.Survey.Description"] = "主CRS座標を適用ステップで使う測量点位置として扱います。",
                ["Georef.AnchorTarget.Project.Title"] = "プロジェクト基点",
                ["Georef.AnchorTarget.Project.Description"] = "主CRS座標を適用ステップで使うプロジェクト基点位置として扱います。",
                ["Georef.CaptureTarget.Primary.Title"] = "主適用アンカー",
                ["Georef.CaptureTarget.Primary.Description"] = "Revit への適用でアンカーとして使う主点を取得します。",
                ["Georef.CaptureTarget.Working.Title"] = "作業用プロジェクト基点",
                ["Georef.CaptureTarget.Working.Description"] = "後続の取込／書き出しワークフローで使う任意の副次プロジェクト基点を取得します。",
                ["Georef.QuickSetup.Title"] = "新規プロジェクト簡易設定",
                ["Georef.QuickSetup.Description"] = "新規プロジェクト向け：CRSを選択し投影座標を入力します。両基点を内部原点に配置します。",
                ["Georef.QuickSetup.StepTitle.CrsAndCoordinates"] = "CRS + 座標",
                ["Georef.QuickSetup.CoordinateHint"] = "選択したCRS（EPSG:{0}）で Easting / Northing を入力します。この座標が Revit 内部原点の実世界位置を定義します。",
                ["Georef.QuickSetup.SelectCrsFirst"] = "上でCRSを選択してから、プロジェクト位置の投影座標を入力してください。",
                ["Georef.QuickSetup.EastingLabel"] = "Easting（X）メートル",
                ["Georef.QuickSetup.NorthingLabel"] = "Northing（Y）メートル",
                ["Georef.QuickSetup.ApplyCoordinates"] = "座標を適用",
                ["Georef.StepDescription.Crs.QuickSetup"] = "プロジェクトCRSを選択し、プロジェクト位置の投影座標を入力します。",

                ["Crs.Title"] = "座標参照系",
                ["Crs.SearchHint"] = "EPSGコード、ゾーン、地名で検索します。",
                ["Crs.Selected"] = "選択中のCRS",
                ["Crs.SelectPrompt"] = "CRSを選択",
                ["Crs.Area"] = "対象範囲",
                ["Crs.Units"] = "単位",
                ["Crs.Datum"] = "測地系",
                ["Crs.Zone"] = "ゾーン",
                ["Mesh.WindowTitle"] = "メッシュインスペクタ",
                ["Validation.WindowTitle"] = "プロジェクト確認",
                ["Tiles.WindowTitle"] = "3D Tiles書き出し",
                ["City.WindowTitle"] = "CityGML書き出し",
                ["Plateau.WindowTitle"] = "PLATEAUコンテキスト取込"
            }
        };
    }
}
