// <auto-generated>
// Generated by tools/MunicipalityCentroidGenerator from PLATEAU 3D Tiles tileset bounds
// (https://api.plateauview.mlit.go.jp/datacatalog/plateau-datasets). Centroid = bounding-box center.
// Do not edit by hand; re-run `dotnet run --project tools/MunicipalityCentroidGenerator` to refresh.
//
// This checked-in copy is intentionally EMPTY. Until the generator is run on a networked machine,
// the PLATEAU Online import map simply shows no municipality pins and the search list still works.
// </auto-generated>
using System.Collections.Generic;

namespace RevitGeoSuite.PlateauImport.Online;

public static class MunicipalityCentroids
{
    /// <summary>Maps a 5-digit PLATEAU area code (ward_code or city_code) to its representative point.</summary>
    public static bool TryGet(string areaCode, out double latitude, out double longitude)
    {
        if (areaCode != null && Centroids.TryGetValue(areaCode, out (double Lat, double Lon) value))
        {
            latitude = value.Lat;
            longitude = value.Lon;
            return true;
        }

        latitude = 0d;
        longitude = 0d;
        return false;
    }

    private static readonly IReadOnlyDictionary<string, (double Lat, double Lon)> Centroids =
        new Dictionary<string, (double Lat, double Lon)>
        {
        };
}
