using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace RevitGeoSuite.SharedUI.Web.Contracts.Generator;

public static class Program
{
    private const string TsExportAttributeName = "RevitGeoSuite.SharedUI.Web.Contracts.TsExportAttribute";
    private const string RpcMethodAttributeName = "RevitGeoSuite.SharedUI.Web.Contracts.RpcMethodAttribute";
    private const string RpcEventAttributeName = "RevitGeoSuite.SharedUI.Web.Contracts.RpcEventAttribute";

    private static readonly NullabilityInfoContext NullabilityContext = new NullabilityInfoContext();

    public static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine("Usage: RevitGeoSuite.SharedUI.Web.Contracts.Generator <assembly-path> <output-path>");
            return 1;
        }

        string assemblyPath = args[0];
        string outputPath = args[1];

        try
        {
            var assembly = Assembly.LoadFrom(assemblyPath);
            var types = assembly.GetTypes()
                .Where(HasTsExportAttribute)
                .OrderBy(t => t.Name)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by RevitGeoSuite.SharedUI.Web.Contracts.Generator");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine();

            foreach (var type in types)
            {
                if (type.IsEnum)
                {
                    GenerateEnum(sb, type);
                }
                else
                {
                    GenerateInterface(sb, type);
                }
                sb.AppendLine();
            }

            GenerateMethodMap(sb, assembly);
            GenerateEventMap(sb, assembly);

            string? outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            File.WriteAllText(outputPath, sb.ToString());
            Console.WriteLine($"Generated {types.Count} TypeScript definitions to {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    private static void GenerateInterface(StringBuilder sb, Type type)
    {
        string name = GetTsExportName(type);

        sb.AppendLine($"export interface {name} {{");

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .OrderBy(p => p.Name);

        foreach (var prop in properties)
        {
            string propName = ToCamelCase(prop.Name);
            string tsType = MapType(prop.PropertyType);
            bool isOptional = IsOptional(prop);

            sb.AppendLine($"  {propName}{(isOptional ? "?" : "")}: {tsType}");
        }

        sb.AppendLine("}");
    }

    private static void GenerateEnum(StringBuilder sb, Type type)
    {
        string name = GetTsExportName(type);

        var values = Enum.GetNames(type);
        string union = string.Join(" | ", values.Select(v => $"'{v}'"));

        sb.AppendLine($"export type {name} = {union}");
    }

    private static void GenerateMethodMap(StringBuilder sb, Assembly assembly)
    {
        var methods = assembly.GetCustomAttributesData()
            .Where(a => a.AttributeType.FullName == RpcMethodAttributeName)
            .Select(ReadRpcMethod)
            .Where(m => m != null)
            .Select(m => m!)
            .OrderBy(a => a.Method, StringComparer.Ordinal)
            .ToList();
        if (methods.Count == 0)
        {
            return;
        }

        sb.AppendLine("export interface RpcMethods {");
        foreach (var method in methods)
        {
            sb.AppendLine($"  '{method.Method}': {{ request: {MapType(method.RequestType)}; response: {MapType(method.ResponseType)} }}");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateEventMap(StringBuilder sb, Assembly assembly)
    {
        var events = assembly.GetCustomAttributesData()
            .Where(a => a.AttributeType.FullName == RpcEventAttributeName)
            .Select(ReadRpcEvent)
            .Where(e => e != null)
            .Select(e => e!)
            .OrderBy(a => a.Method, StringComparer.Ordinal)
            .ToList();
        if (events.Count == 0)
        {
            return;
        }

        sb.AppendLine("export interface RpcEvents {");
        foreach (var evt in events)
        {
            sb.AppendLine($"  '{evt.Method}': {MapType(evt.PayloadType)}");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>A property is optional in TS when it's a nullable value type or a nullable reference type (NRT).</summary>
    private static bool IsOptional(PropertyInfo prop)
    {
        Type type = prop.PropertyType;
        if (type.IsValueType)
        {
            return Nullable.GetUnderlyingType(type) != null;
        }

        try
        {
            return NullabilityContext.Create(prop).ReadState == NullabilityState.Nullable;
        }
        catch
        {
            // If nullability metadata is unavailable, default to required (matches the C# non-null intent).
            return false;
        }
    }

    private static string MapType(Type type)
    {
        if (type == typeof(void))
            return "void";

        if (type == typeof(string))
            return "string";

        if (type == typeof(bool))
            return "boolean";

        if (type == typeof(int) || type == typeof(long) || type == typeof(float) ||
            type == typeof(double) || type == typeof(decimal) || type == typeof(short) ||
            type == typeof(byte))
            return "number";

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return "string";

        if (type == typeof(object))
            return "unknown";

        if (type.IsArray)
        {
            var elementType = type.GetElementType()!;
            return $"{MapType(elementType)}[]";
        }

        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();

            if (genericDef == typeof(Nullable<>))
            {
                var innerType = type.GetGenericArguments()[0];
                return MapType(innerType);
            }

            if (genericDef == typeof(List<>) || genericDef == typeof(IList<>) ||
                genericDef == typeof(IEnumerable<>) || genericDef == typeof(IReadOnlyList<>) ||
                genericDef == typeof(IReadOnlyCollection<>) || genericDef == typeof(ICollection<>))
            {
                var elementType = type.GetGenericArguments()[0];
                return $"{MapType(elementType)}[]";
            }

            if (genericDef == typeof(Dictionary<,>) || genericDef == typeof(IDictionary<,>) ||
                genericDef == typeof(IReadOnlyDictionary<,>))
            {
                var keyType = type.GetGenericArguments()[0];
                var valueType = type.GetGenericArguments()[1];
                return $"Record<{MapType(keyType)}, {MapType(valueType)}>";
            }
        }

        if (type.IsEnum)
        {
            return type.Name;
        }

        if (HasTsExportAttribute(type))
        {
            return GetTsExportName(type);
        }

        return "unknown";
    }

    private static bool HasTsExportAttribute(Type type)
    {
        return type.GetCustomAttributesData().Any(a => a.AttributeType.FullName == TsExportAttributeName);
    }

    private static string GetTsExportName(Type type)
    {
        var attr = type.GetCustomAttributesData()
            .FirstOrDefault(a => a.AttributeType.FullName == TsExportAttributeName);

        string? name = attr?.NamedArguments
            .FirstOrDefault(a => a.MemberName == "Name")
            .TypedValue.Value as string;

        return string.IsNullOrWhiteSpace(name) ? type.Name : name;
    }

    private static RpcMethodContract? ReadRpcMethod(CustomAttributeData attr)
    {
        if (attr.ConstructorArguments.Count != 3)
        {
            return null;
        }

        string? method = attr.ConstructorArguments[0].Value as string;
        Type? requestType = attr.ConstructorArguments[1].Value as Type;
        Type? responseType = attr.ConstructorArguments[2].Value as Type;

        return string.IsNullOrWhiteSpace(method) || requestType == null || responseType == null
            ? null
            : new RpcMethodContract(method, requestType, responseType);
    }

    private static RpcEventContract? ReadRpcEvent(CustomAttributeData attr)
    {
        if (attr.ConstructorArguments.Count != 2)
        {
            return null;
        }

        string? method = attr.ConstructorArguments[0].Value as string;
        Type? payloadType = attr.ConstructorArguments[1].Value as Type;

        return string.IsNullOrWhiteSpace(method) || payloadType == null
            ? null
            : new RpcEventContract(method, payloadType);
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        if (name.Length == 1)
            return name.ToLowerInvariant();

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private sealed record RpcMethodContract(string Method, Type RequestType, Type ResponseType);

    private sealed record RpcEventContract(string Method, Type PayloadType);
}
