using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using RevitGeoSuite.Core.Plateau.Catalog;

namespace RevitGeoSuite.Tools.MunicipalityCentroidGenerator;

internal static class Program
{
    private const int MaxConcurrency = 8;

    private static async Task<int> Main()
    {
        Console.OutputEncoding = Encoding.UTF8;

        string repoRoot = FindRepoRoot();
        string outFile = Path.Combine(repoRoot, "src", "RevitGeoSuite.PlateauImport", "Online", "MunicipalityCentroids.cs");

        var httpClient = new PlateauHttpClient();
        var apiClient = new PlateauApiClient(httpClient);

        Console.WriteLine("Fetching PLATEAU catalog…");
        PlateauCatalog catalog = await apiClient.FetchCatalogAsync().ConfigureAwait(false);
        Console.WriteLine($"Catalog: {catalog.AreaOptions.Count} area(s), {catalog.Datasets.Count} dataset(s).");

        var geometryService = new PlateauAreaGeometryService(httpClient);
        var centroids = new SortedDictionary<string, (double Lat, double Lon)>(StringComparer.Ordinal);
        var sync = new object();
        var gate = new SemaphoreSlim(MaxConcurrency);
        int processed = 0;
        int missing = 0;

        IEnumerable<Task> tasks = catalog.AreaOptions.Select(async area =>
        {
            await gate.WaitAsync().ConfigureAwait(false);
            try
            {
                PlateauAreaBounds? bounds = await geometryService.GetBoundsAsync(area, catalog).ConfigureAwait(false);
                if (bounds is not null)
                {
                    double lat = (bounds.SouthDeg + bounds.NorthDeg) / 2d;
                    double lon = (bounds.WestDeg + bounds.EastDeg) / 2d;
                    lock (sync)
                    {
                        centroids[area.Code] = (lat, lon);
                    }
                }
                else
                {
                    Interlocked.Increment(ref missing);
                }
            }
            catch (Exception ex)
            {
                Interlocked.Increment(ref missing);
                Console.WriteLine($"  skip {area.Code} ({area.Label}): {ex.Message}");
            }
            finally
            {
                int n = Interlocked.Increment(ref processed);
                if (n % 25 == 0)
                {
                    Console.WriteLine($"  {n}/{catalog.AreaOptions.Count}…");
                }

                gate.Release();
            }
        });

        await Task.WhenAll(tasks).ConfigureAwait(false);

        Console.WriteLine($"Resolved {centroids.Count} centroid(s); {missing} area(s) had no usable bounds.");
        WriteFile(outFile, centroids);
        Console.WriteLine($"Wrote {outFile}");
        return 0;
    }

    private static void WriteFile(string outFile, SortedDictionary<string, (double Lat, double Lon)> centroids)
    {
        var sb = new StringBuilder();
        sb.Append(
@"// <auto-generated>
// Generated by tools/MunicipalityCentroidGenerator from PLATEAU 3D Tiles tileset bounds
// (https://api.plateauview.mlit.go.jp/datacatalog/plateau-datasets). Centroid = bounding-box center.
// Do not edit by hand; re-run `dotnet run --project tools/MunicipalityCentroidGenerator` to refresh.
// </auto-generated>
using System.Collections.Generic;

namespace RevitGeoSuite.PlateauImport.Online;

public static class MunicipalityCentroids
{
    /// <summary>Maps a 5-digit PLATEAU area code (ward_code or city_code) to its representative point.</summary>
    public static bool TryGet(string areaCode, out double latitude, out double longitude)
    {
        if (areaCode != null && Centroids.TryGetValue(areaCode, out (double Lat, double Lon) value))
        {
            latitude = value.Lat;
            longitude = value.Lon;
            return true;
        }

        latitude = 0d;
        longitude = 0d;
        return false;
    }

    private static readonly IReadOnlyDictionary<string, (double Lat, double Lon)> Centroids =
        new Dictionary<string, (double Lat, double Lon)>
        {
");

        foreach (KeyValuePair<string, (double Lat, double Lon)> kvp in centroids)
        {
            sb.Append("            [\"")
              .Append(kvp.Key)
              .Append("\"] = (")
              .Append(kvp.Value.Lat.ToString("R", CultureInfo.InvariantCulture))
              .Append(", ")
              .Append(kvp.Value.Lon.ToString("R", CultureInfo.InvariantCulture))
              .Append("),\n");
        }

        sb.Append(
@"        };
}
");

        Directory.CreateDirectory(Path.GetDirectoryName(outFile)!);
        File.WriteAllText(outFile, sb.ToString().Replace("\r\n", "\n"), new UTF8Encoding(false));
    }

    private static string FindRepoRoot()
    {
        string? dir = AppContext.BaseDirectory;
        while (dir is not null && !File.Exists(Path.Combine(dir, "RevitGeoSuite.sln")))
        {
            dir = Path.GetDirectoryName(dir);
        }

        return dir ?? throw new InvalidOperationException("Could not locate the repository root (RevitGeoSuite.sln).");
    }
}
